// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_AMBIENTES2_screen_init(void)
{
    ui_AMBIENTES2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AMBIENTES2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AMBIENTES2, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AMBIENTES2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButton = lv_button_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_MenuButton, 100);
    lv_obj_set_height(ui_MenuButton, 59);
    lv_obj_set_x(ui_MenuButton, 175);
    lv_obj_set_y(ui_MenuButton, -125);
    lv_obj_set_align(ui_MenuButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButton, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_MenuButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "MENU");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPERATURAS2 = lv_obj_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_TEMPERATURAS2, 210);
    lv_obj_set_height(ui_TEMPERATURAS2, 242);
    lv_obj_set_x(ui_TEMPERATURAS2, -105);
    lv_obj_set_y(ui_TEMPERATURAS2, 31);
    lv_obj_set_align(ui_TEMPERATURAS2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TEMPERATURAS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TEMPERATURAS2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TEMPERATURAS2, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TEMPERATURAS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TEMPERATURAS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TEMPERATURAS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_tamperaturaindicator2 = lv_spinner_create(ui_TEMPERATURAS2);
    //lv_spinner_set_anim_params(ui_tamperaturaindicator2, 1000, 90);
    lv_obj_set_width(ui_tamperaturaindicator2, 170);
    lv_obj_set_height(ui_tamperaturaindicator2, 174);
    lv_obj_set_x(ui_tamperaturaindicator2, 1);
    lv_obj_set_y(ui_tamperaturaindicator2, -14);
    lv_obj_set_align(ui_tamperaturaindicator2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tamperaturaindicator2, LV_OBJ_FLAG_CLICKABLE);      /// Flags*/

    ui_HUMEDADS2 = lv_obj_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_HUMEDADS2, 210);
    lv_obj_set_height(ui_HUMEDADS2, 242);
    lv_obj_set_x(ui_HUMEDADS2, 114);
    lv_obj_set_y(ui_HUMEDADS2, 31);
    lv_obj_set_align(ui_HUMEDADS2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HUMEDADS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HUMEDADS2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HUMEDADS2, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HUMEDADS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HUMEDADS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HUMEDADS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_humedadindicator2 = lv_spinner_create(ui_HUMEDADS2);
    //lv_spinner_set_anim_params(ui_humedadindicator2, 1000, 90);
    lv_obj_set_width(ui_humedadindicator2, 170);
    lv_obj_set_height(ui_humedadindicator2, 174);
    lv_obj_set_x(ui_humedadindicator2, 1);
    lv_obj_set_y(ui_humedadindicator2, -13);
    lv_obj_set_align(ui_humedadindicator2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humedadindicator2, LV_OBJ_FLAG_CLICKABLE);      /// Flags*/

    ui_temperaturatext2 = lv_label_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_temperaturatext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturatext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturatext2, -104);
    lv_obj_set_y(ui_temperaturatext2, 121);
    lv_obj_set_align(ui_temperaturatext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturatext2, "TEMPERATURA");
    lv_obj_set_style_text_color(ui_temperaturatext2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperaturatext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperaturatext2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humedadtext2 = lv_label_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_humedadtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humedadtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humedadtext2, 116);
    lv_obj_set_y(ui_humedadtext2, 121);
    lv_obj_set_align(ui_humedadtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humedadtext2, "HUMEDAD");
    lv_obj_set_style_text_color(ui_humedadtext2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humedadtext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humedadtext2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton = lv_button_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_backButton, 100);
    lv_obj_set_height(ui_backButton, 59);
    lv_obj_set_x(ui_backButton, -174);
    lv_obj_set_y(ui_backButton, -125);
    lv_obj_set_align(ui_backButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "BACK");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORtempS2 = lv_label_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_VALORtempS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORtempS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORtempS2, -107);
    lv_obj_set_y(ui_VALORtempS2, 13);
    lv_obj_set_align(ui_VALORtempS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORtempS2, SectorS2Amb.temp_amb);
    lv_obj_set_style_text_color(ui_VALORtempS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORtempS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORtempS2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORhumS2 = lv_label_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_VALORhumS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORhumS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORhumS2, 117);
    lv_obj_set_y(ui_VALORhumS2, 13);
    lv_obj_set_align(ui_VALORhumS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORhumS2, SectorS2Amb.hum_amb);
    lv_obj_set_style_text_color(ui_VALORhumS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORhumS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORhumS2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDPVS2 = lv_obj_create(ui_AMBIENTES2);
    lv_obj_set_width(ui_PanelDPVS2, 230);
    lv_obj_set_height(ui_PanelDPVS2, 58);
    lv_obj_set_x(ui_PanelDPVS2, 0);
    lv_obj_set_y(ui_PanelDPVS2, -125);
    lv_obj_set_align(ui_PanelDPVS2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelDPVS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDPVS2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDPVS2, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDPVS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDPVS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDPVS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPV2text = lv_label_create(ui_PanelDPVS2);
    lv_obj_set_width(ui_DPV2text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPV2text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPV2text, -60);
    lv_obj_set_y(ui_DPV2text, 0);
    lv_obj_set_align(ui_DPV2text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPV2text, "DPV :");
    lv_obj_set_style_text_color(ui_DPV2text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPV2text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPV2text, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORDPVS2 = lv_label_create(ui_PanelDPVS2);
    lv_obj_set_width(ui_VALORDPVS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORDPVS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORDPVS2, 25);
    lv_obj_set_y(ui_VALORDPVS2, 0);
    lv_obj_set_align(ui_VALORDPVS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORDPVS2, SectorS2Amb.dpv);
    lv_obj_set_style_text_color(ui_VALORDPVS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORDPVS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORDPVS2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuButton, ui_event_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);

}
