// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_AMBIENTES1_screen_init(void)
{
    ui_AMBIENTES1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AMBIENTES1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AMBIENTES1, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AMBIENTES1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPERATURA1 = lv_obj_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_TEMPERATURA1, 210);
    lv_obj_set_height(ui_TEMPERATURA1, 242);
    lv_obj_set_x(ui_TEMPERATURA1, -105);
    lv_obj_set_y(ui_TEMPERATURA1, 31);
    lv_obj_set_align(ui_TEMPERATURA1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TEMPERATURA1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TEMPERATURA1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TEMPERATURA1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TEMPERATURA1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TEMPERATURA1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TEMPERATURA1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TEMPERATURA1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TEMPERATURA1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_temperaturaindicator1 = lv_spinner_create(ui_TEMPERATURA1);
    //lv_spinner_set_anim_params(ui_temperaturaindicator1, 1000, 90);
    lv_obj_set_width(ui_temperaturaindicator1, 170);
    lv_obj_set_height(ui_temperaturaindicator1, 174);
    lv_obj_set_x(ui_temperaturaindicator1, -102);
    lv_obj_set_y(ui_temperaturaindicator1, 10);
    lv_obj_set_align(ui_temperaturaindicator1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_temperaturaindicator1, LV_OBJ_FLAG_CLICKABLE);      /// Flags*/

    ui_HUMEDAD1 = lv_obj_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_HUMEDAD1, 210);
    lv_obj_set_height(ui_HUMEDAD1, 242);
    lv_obj_set_x(ui_HUMEDAD1, 118);
    lv_obj_set_y(ui_HUMEDAD1, 32);
    lv_obj_set_align(ui_HUMEDAD1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HUMEDAD1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HUMEDAD1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_HUMEDAD1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HUMEDAD1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HUMEDAD1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HUMEDAD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HUMEDAD1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HUMEDAD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_humedadindicator1 = lv_spinner_create(ui_HUMEDAD1);
    //lv_spinner_set_anim_params(ui_humedadindicator1, 1000, 90);
    lv_obj_set_width(ui_humedadindicator1, 170);
    lv_obj_set_height(ui_humedadindicator1, 174);
    lv_obj_set_x(ui_humedadindicator1, 207);
    lv_obj_set_y(ui_humedadindicator1, 30);
    lv_obj_set_align(ui_humedadindicator1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humedadindicator1, LV_OBJ_FLAG_CLICKABLE);      /// Flags*/

    ui_botonmenu1 = lv_button_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_botonmenu1, 100);
    lv_obj_set_height(ui_botonmenu1, 59);
    lv_obj_set_x(ui_botonmenu1, 175);
    lv_obj_set_y(ui_botonmenu1, -125);
    lv_obj_set_align(ui_botonmenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonmenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_botonmenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botonmenu1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botonmenu1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botonmenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_botonmenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_botonmenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   // lv_obj_set_style_shadow_color(ui_botonmenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_botonmenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menutext1 = lv_label_create(ui_botonmenu1);
    lv_obj_set_width(ui_menutext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menutext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menutext1, "MENU");
    lv_obj_set_style_text_font(ui_menutext1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humedadtext = lv_label_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_humedadtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humedadtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humedadtext, 120);
    lv_obj_set_y(ui_humedadtext, 121);
    lv_obj_set_align(ui_humedadtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humedadtext, "HUMEDAD");
    lv_obj_set_style_text_color(ui_humedadtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humedadtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_humedadtext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humedadtext, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_Button9, 100);
    lv_obj_set_height(ui_Button9, 59);
    lv_obj_set_x(ui_Button9, -174);
    lv_obj_set_y(ui_Button9, -125);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botonbacktext = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_botonbacktext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_botonbacktext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_botonbacktext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_botonbacktext, "BACK");
    lv_obj_set_style_text_font(ui_botonbacktext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatura1text = lv_label_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_temperatura1text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatura1text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatura1text, -104);
    lv_obj_set_y(ui_temperatura1text, 121);
    lv_obj_set_align(ui_temperatura1text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatura1text, "TEMPERATURA");
    lv_obj_set_style_text_color(ui_temperatura1text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatura1text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_temperatura1text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatura1text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORtempS1 = lv_label_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_VALORtempS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORtempS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORtempS1, -107);
    lv_obj_set_y(ui_VALORtempS1, 13);
    lv_obj_set_align(ui_VALORtempS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORtempS1, SectorS1Amb.temp_amb);
    lv_obj_set_style_text_color(ui_VALORtempS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORtempS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORtempS1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORhumS1 = lv_label_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_VALORhumS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORhumS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORhumS1, 117);
    lv_obj_set_y(ui_VALORhumS1, 13);
    lv_obj_set_align(ui_VALORhumS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORhumS1, SectorS1Amb.hum_amb);
    lv_obj_set_style_text_color(ui_VALORhumS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORhumS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORhumS1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDPVS1 = lv_obj_create(ui_AMBIENTES1);
    lv_obj_set_width(ui_PanelDPVS1, 230);
    lv_obj_set_height(ui_PanelDPVS1, 58);
    lv_obj_set_x(ui_PanelDPVS1, 0);
    lv_obj_set_y(ui_PanelDPVS1, -125);
    lv_obj_set_align(ui_PanelDPVS1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelDPVS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDPVS1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDPVS1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDPVS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDPVS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDPVS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPV1text = lv_label_create(ui_PanelDPVS1);
    lv_obj_set_width(ui_DPV1text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPV1text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPV1text, -60);
    lv_obj_set_y(ui_DPV1text, 0);
    lv_obj_set_align(ui_DPV1text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPV1text, "DPV :");
    lv_obj_set_style_text_color(ui_DPV1text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPV1text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPV1text, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORDPVS1 = lv_label_create(ui_PanelDPVS1);
    lv_obj_set_width(ui_VALORDPVS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORDPVS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORDPVS1, 25);
    lv_obj_set_y(ui_VALORDPVS1, 0);
    lv_obj_set_align(ui_VALORDPVS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORDPVS1, SectorS1Amb.dpv);
    lv_obj_set_style_text_color(ui_VALORDPVS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORDPVS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORDPVS1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botonmenu1, ui_event_botonmenu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
