// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BalanceDiarioS1_screen_init(void)
{
    ui_BalanceDiarioS1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BalanceDiarioS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BalanceDiarioS1, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BalanceDiarioS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_BalanceDiarioS1);
    lv_obj_set_width(ui_Panel18, 237);
    lv_obj_set_height(ui_Panel18, 155);
    lv_obj_set_x(ui_Panel18, -120);
    lv_obj_set_y(ui_Panel18, 80);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceTempTextMinS1 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_BalanceTempTextMinS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceTempTextMinS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceTempTextMinS1, 0);
    lv_obj_set_y(ui_BalanceTempTextMinS1, -15);
    lv_obj_set_align(ui_BalanceTempTextMinS1, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceTempTextMinS1, BalancesS1.temp_min);
    lv_obj_set_style_text_color(ui_BalanceTempTextMinS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceTempTextMinS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceTempTextMinS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTempMinimaS1 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_TextTempMinimaS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTempMinimaS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTempMinimaS1, 0);
    lv_obj_set_y(ui_TextTempMinimaS1, 11);
    lv_obj_set_align(ui_TextTempMinimaS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextTempMinimaS1, "\nTemperatura\n     Minima");
    lv_obj_set_style_text_color(ui_TextTempMinimaS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTempMinimaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTempMinimaS1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_BalanceDiarioS1);
    lv_obj_set_width(ui_Panel29, 237);
    lv_obj_set_height(ui_Panel29, 155);
    lv_obj_set_x(ui_Panel29, -119);
    lv_obj_set_y(ui_Panel29, -78);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel29, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceTempTextMaxS1 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_BalanceTempTextMaxS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceTempTextMaxS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceTempTextMaxS1, 0);
    lv_obj_set_y(ui_BalanceTempTextMaxS1, -15);
    lv_obj_set_align(ui_BalanceTempTextMaxS1, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceTempTextMaxS1, BalancesS1.temp_max);
    lv_obj_set_style_text_color(ui_BalanceTempTextMaxS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceTempTextMaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceTempTextMaxS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTempMaximaS1 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_TextTempMaximaS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTempMaximaS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTempMaximaS1, 0);
    lv_obj_set_y(ui_TextTempMaximaS1, 11);
    lv_obj_set_align(ui_TextTempMaximaS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextTempMaximaS1, "\nTemperatura\n     Maxima");
    lv_obj_set_style_text_color(ui_TextTempMaximaS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTempMaximaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTempMaximaS1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_BalanceDiarioS1);
    lv_obj_set_width(ui_Panel30, 237);
    lv_obj_set_height(ui_Panel30, 155);
    lv_obj_set_x(ui_Panel30, 120);
    lv_obj_set_y(ui_Panel30, 80);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel30, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceHumTextMinS1 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_BalanceHumTextMinS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceHumTextMinS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceHumTextMinS1, 0);
    lv_obj_set_y(ui_BalanceHumTextMinS1, -15);
    lv_obj_set_align(ui_BalanceHumTextMinS1, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceHumTextMinS1, BalancesS1.hum_min);
    lv_obj_set_style_text_color(ui_BalanceHumTextMinS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceHumTextMinS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceHumTextMinS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHumMinimaS1 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_TextHumMinimaS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHumMinimaS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHumMinimaS1, 0);
    lv_obj_set_y(ui_TextHumMinimaS1, 24);
    lv_obj_set_align(ui_TextHumMinimaS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHumMinimaS1, "Humedad\n  Minima");
    lv_obj_set_style_text_color(ui_TextHumMinimaS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHumMinimaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHumMinimaS1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel31 = lv_obj_create(ui_BalanceDiarioS1);
    lv_obj_set_width(ui_Panel31, 237);
    lv_obj_set_height(ui_Panel31, 155);
    lv_obj_set_x(ui_Panel31, 120);
    lv_obj_set_y(ui_Panel31, -78);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel31, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceHumMaxS1 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_BalanceHumMaxS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceHumMaxS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceHumMaxS1, 0);
    lv_obj_set_y(ui_BalanceHumMaxS1, -15);
    lv_obj_set_align(ui_BalanceHumMaxS1, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceHumMaxS1, BalancesS1.hum_max);
    lv_obj_set_style_text_color(ui_BalanceHumMaxS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceHumMaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceHumMaxS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHumMaximaS1 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_TextHumMaximaS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHumMaximaS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHumMaximaS1, 0);
    lv_obj_set_y(ui_TextHumMaximaS1, 29);
    lv_obj_set_align(ui_TextHumMaximaS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHumMaximaS1, "Humedad\n  Maxima");
    lv_obj_set_style_text_color(ui_TextHumMaximaS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHumMaximaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHumMaximaS1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBack3 = lv_button_create(ui_BalanceDiarioS1);
    lv_obj_set_width(ui_ButtonBack3, 100);
    lv_obj_set_height(ui_ButtonBack3, 70);
    lv_obj_set_x(ui_ButtonBack3, 0);
    lv_obj_set_y(ui_ButtonBack3, -120);
    lv_obj_set_align(ui_ButtonBack3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBack3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonBack3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBack3, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonBack3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonBack3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ButtonBack3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "BACK");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonBack3, ui_event_ButtonBack3, LV_EVENT_ALL, NULL);

}
