// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BalanceDiarioS2_screen_init(void)
{
    ui_BalanceDiarioS2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BalanceDiarioS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BalanceDiarioS2, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BalanceDiarioS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_BalanceDiarioS2);
    lv_obj_set_width(ui_Panel32, 237);
    lv_obj_set_height(ui_Panel32, 155);
    lv_obj_set_x(ui_Panel32, -120);
    lv_obj_set_y(ui_Panel32, 80);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel32, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceTempTextMinS2 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_BalanceTempTextMinS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceTempTextMinS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceTempTextMinS2, 0);
    lv_obj_set_y(ui_BalanceTempTextMinS2, -15);
    lv_obj_set_align(ui_BalanceTempTextMinS2, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceTempTextMinS2, BalancesS2.temp_min);
    lv_obj_set_style_text_color(ui_BalanceTempTextMinS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceTempTextMinS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceTempTextMinS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTempMinimaS2 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_TextTempMinimaS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTempMinimaS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTempMinimaS2, 0);
    lv_obj_set_y(ui_TextTempMinimaS2, 11);
    lv_obj_set_align(ui_TextTempMinimaS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextTempMinimaS2, "\nTemperatura\n     Minima");
    lv_obj_set_style_text_color(ui_TextTempMinimaS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTempMinimaS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTempMinimaS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_BalanceDiarioS2);
    lv_obj_set_width(ui_Panel33, 237);
    lv_obj_set_height(ui_Panel33, 155);
    lv_obj_set_x(ui_Panel33, -119);
    lv_obj_set_y(ui_Panel33, -78);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel33, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceTempTextMaxS2 = lv_label_create(ui_Panel33);
    lv_obj_set_width(ui_BalanceTempTextMaxS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceTempTextMaxS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceTempTextMaxS2, 0);
    lv_obj_set_y(ui_BalanceTempTextMaxS2, -15);
    lv_obj_set_align(ui_BalanceTempTextMaxS2, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceTempTextMaxS2, BalancesS2.temp_max);
    lv_obj_set_style_text_color(ui_BalanceTempTextMaxS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceTempTextMaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceTempTextMaxS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTempMaximaS2 = lv_label_create(ui_Panel33);
    lv_obj_set_width(ui_TextTempMaximaS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTempMaximaS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTempMaximaS2, 0);
    lv_obj_set_y(ui_TextTempMaximaS2, 11);
    lv_obj_set_align(ui_TextTempMaximaS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextTempMaximaS2, "\nTemperatura\n     Maxima");
    lv_obj_set_style_text_color(ui_TextTempMaximaS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTempMaximaS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTempMaximaS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel34 = lv_obj_create(ui_BalanceDiarioS2);
    lv_obj_set_width(ui_Panel34, 237);
    lv_obj_set_height(ui_Panel34, 155);
    lv_obj_set_x(ui_Panel34, 120);
    lv_obj_set_y(ui_Panel34, 80);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel34, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel34, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceHumTextMinS2 = lv_label_create(ui_Panel34);
    lv_obj_set_width(ui_BalanceHumTextMinS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceHumTextMinS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceHumTextMinS2, 0);
    lv_obj_set_y(ui_BalanceHumTextMinS2, -15);
    lv_obj_set_align(ui_BalanceHumTextMinS2, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceHumTextMinS2, BalancesS2.hum_min);
    lv_obj_set_style_text_color(ui_BalanceHumTextMinS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceHumTextMinS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceHumTextMinS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHumMinimaS2 = lv_label_create(ui_Panel34);
    lv_obj_set_width(ui_TextHumMinimaS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHumMinimaS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHumMinimaS2, 0);
    lv_obj_set_y(ui_TextHumMinimaS2, 24);
    lv_obj_set_align(ui_TextHumMinimaS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHumMinimaS2, "Humedad\n  Minima");
    lv_obj_set_style_text_color(ui_TextHumMinimaS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHumMinimaS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHumMinimaS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_BalanceDiarioS2);
    lv_obj_set_width(ui_Panel35, 237);
    lv_obj_set_height(ui_Panel35, 155);
    lv_obj_set_x(ui_Panel35, 120);
    lv_obj_set_y(ui_Panel35, -78);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel35, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceHumMaxS2 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_BalanceHumMaxS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceHumMaxS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceHumMaxS2, 0);
    lv_obj_set_y(ui_BalanceHumMaxS2, -15);
    lv_obj_set_align(ui_BalanceHumMaxS2, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_BalanceHumMaxS2, BalancesS2.hum_max);
    lv_obj_set_style_text_color(ui_BalanceHumMaxS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceHumMaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceHumMaxS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHumMaximaS2 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_TextHumMaximaS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHumMaximaS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHumMaximaS2, 0);
    lv_obj_set_y(ui_TextHumMaximaS2, 29);
    lv_obj_set_align(ui_TextHumMaximaS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHumMaximaS2, "Humedad\n  Maxima");
    lv_obj_set_style_text_color(ui_TextHumMaximaS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHumMaximaS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHumMaximaS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBack4 = lv_button_create(ui_BalanceDiarioS2);
    lv_obj_set_width(ui_ButtonBack4, 100);
    lv_obj_set_height(ui_ButtonBack4, 70);
    lv_obj_set_x(ui_ButtonBack4, 0);
    lv_obj_set_y(ui_ButtonBack4, -120);
    lv_obj_set_align(ui_ButtonBack4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBack4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBack4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonBack4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBack4, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonBack4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonBack4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ButtonBack4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "BACK");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonBack4, ui_event_ButtonBack4, LV_EVENT_ALL, NULL);

}
