// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "misc/lv_event.h"

void ui_CONFIGURACION_screen_init(void)
{
    ui_CONFIGURACION = lv_obj_create(NULL);
    ui_limpiar_sombra(ui_CONFIGURACION);
    lv_obj_remove_flag(ui_CONFIGURACION, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONFIGURACION, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONFIGURACION, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_Panel1 = lv_obj_create(ui_CONFIGURACION);
    ui_limpiar_sombra(ui_Panel1);
    lv_obj_set_width(ui_Panel1, 215);
    lv_obj_set_height(ui_Panel1, 118);
    lv_obj_set_x(ui_Panel1, -112);
    lv_obj_set_y(ui_Panel1, -31);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	
    ui_ButtonNebulizar = lv_button_create(ui_CONFIGURACION);
    ui_limpiar_sombra(ui_ButtonNebulizar);
    lv_obj_set_width(ui_ButtonNebulizar, 188);
    lv_obj_set_height(ui_ButtonNebulizar, 80);
    lv_obj_set_x(ui_ButtonNebulizar, -111);
    lv_obj_set_y(ui_ButtonNebulizar, -32);
    lv_obj_set_align(ui_ButtonNebulizar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNebulizar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonNebulizar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonNebulizar, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonNebulizar, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonNebulizar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonNebulizar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonNebulizar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonNebulizar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nebulizartext = lv_label_create(ui_ButtonNebulizar);
    ui_limpiar_sombra(ui_Nebulizartext);
    lv_obj_set_width(ui_Nebulizartext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Nebulizartext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Nebulizartext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Nebulizartext, "NEBULIZAR");
    lv_obj_set_style_text_color(ui_Nebulizartext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Nebulizartext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Nebulizartext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_CONFIGURACION);
    ui_limpiar_sombra(ui_Panel2);
    lv_obj_set_width(ui_Panel2, 215);
    lv_obj_set_height(ui_Panel2, 118);
    lv_obj_set_x(ui_Panel2, 118);
    lv_obj_set_y(ui_Panel2, -31);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRangos = lv_button_create(ui_CONFIGURACION);
    ui_limpiar_sombra(ui_ButtonRangos);
    lv_obj_set_width(ui_ButtonRangos, 188);
    lv_obj_set_height(ui_ButtonRangos, 80);
    lv_obj_set_x(ui_ButtonRangos, 120);
    lv_obj_set_y(ui_ButtonRangos, -32);
    lv_obj_set_align(ui_ButtonRangos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRangos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRangos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonRangos, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRangos, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRangos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonRangos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonRangos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonRangos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RANGOStext = lv_label_create(ui_ButtonRangos);
    ui_limpiar_sombra(ui_RANGOStext);
    lv_obj_set_width(ui_RANGOStext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RANGOStext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RANGOStext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RANGOStext, "RANGOS");
    lv_obj_set_style_text_color(ui_RANGOStext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RANGOStext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RANGOStext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_CONFIGURACION);
     ui_limpiar_sombra(ui_Panel6);
    lv_obj_set_width(ui_Panel6, 446);
    lv_obj_set_height(ui_Panel6, 106);
    lv_obj_set_x(ui_Panel6, 3);
    lv_obj_set_y(ui_Panel6, 89);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchDesactivarAutomatismo = lv_switch_create(ui_Panel6);
    ui_limpiar_sombra(ui_SwitchDesactivarAutomatismo);
    lv_obj_set_width(ui_SwitchDesactivarAutomatismo, 172);
    lv_obj_set_height(ui_SwitchDesactivarAutomatismo, 76);
    lv_obj_set_x(ui_SwitchDesactivarAutomatismo, 120);
    lv_obj_set_y(ui_SwitchDesactivarAutomatismo, 0);
    lv_obj_set_align(ui_SwitchDesactivarAutomatismo, LV_ALIGN_CENTER);
	lv_obj_clear_flag(ui_SwitchDesactivarAutomatismo, LV_OBJ_FLAG_CHECKABLE);//
	
    ui_Label14 = lv_label_create(ui_Panel6);
    ui_limpiar_sombra(ui_Label14);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -95);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "  Desactivar \nAutomatismo");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMenu2 = lv_button_create(ui_CONFIGURACION);
    ui_limpiar_sombra(ui_ButtonMenu2);
    lv_obj_set_width(ui_ButtonMenu2, 100);
    lv_obj_set_height(ui_ButtonMenu2, 59);
    lv_obj_set_x(ui_ButtonMenu2, 5);
    lv_obj_set_y(ui_ButtonMenu2, -125);
    lv_obj_set_align(ui_ButtonMenu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMenu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonMenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMenu2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMenu2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonMenu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MENUText2 = lv_label_create(ui_ButtonMenu2);
    ui_limpiar_sombra(ui_MENUText2);
    lv_obj_set_width(ui_MENUText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MENUText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MENUText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MENUText2, "MENU");
    lv_obj_set_style_text_color(ui_MENUText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MENUText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MENUText2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonNebulizar, ui_event_ButtonNebulizar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRangos, ui_event_ButtonRangos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MENUText2, ui_event_MENUText2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMenu2, ui_event_ButtonMenu2, LV_EVENT_ALL, NULL);
    //
 //   lv_obj_add_event_cb(ui_SwitchDesactivarAutomatismo, ui_event_SwitchDesactivarAutomatismo, LV_STATE_CHECKED|| !LV_STATE_CHECKED, NULL);
//lv_obj_add_event_cb(ui_SwitchDesactivarAutomatismo, ui_event_SwitchDesactivarAutomatismo, LV_EVENT_VALUE_CHANGED, NULL);
lv_obj_add_event_cb(ui_SwitchDesactivarAutomatismo, ui_event_SwitchDesactivarAutomatismo, LV_EVENT_PRESSED, NULL);
}
