// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_GraficasAmbiente_screen_init(void)
{
    ui_GraficasAmbiente = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GraficasAmbiente, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GraficasAmbiente, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GraficasAmbiente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa4 = lv_button_create(ui_GraficasAmbiente);
    lv_obj_set_width(ui_MenuButtomRa4, 100);
    lv_obj_set_height(ui_MenuButtomRa4, 59);
    lv_obj_set_x(ui_MenuButtomRa4, 189);
    lv_obj_set_y(ui_MenuButtomRa4, -129);
    lv_obj_set_align(ui_MenuButtomRa4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa4, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menutext6 = lv_label_create(ui_MenuButtomRa4);
    lv_obj_set_width(ui_menutext6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutext6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menutext6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menutext6, "MENU");
    lv_obj_set_style_text_color(ui_menutext6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menutext6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menutext6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_GraficasAmbiente);
    lv_obj_set_width(ui_Panel11, 394);
    lv_obj_set_height(ui_Panel11, 230);
    lv_obj_set_x(ui_Panel11, -35);
    lv_obj_set_y(ui_Panel11, 32);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTempS1 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_ButtonTempS1, 180);
    lv_obj_set_height(ui_ButtonTempS1, 100);
    lv_obj_set_x(ui_ButtonTempS1, -97);
    lv_obj_set_y(ui_ButtonTempS1, -54);
    lv_obj_set_align(ui_ButtonTempS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTempS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTempS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTempS1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTempS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTempS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonTempS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonTempS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtomTempS1Text = lv_label_create(ui_ButtonTempS1);
    lv_obj_set_width(ui_ButtomTempS1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtomTempS1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtomTempS1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtomTempS1Text, "GRAFICA \nSECTOR 1");
    lv_obj_set_style_text_color(ui_ButtomTempS1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtomTempS1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtomTempS1Text, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTempS2 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_ButtonTempS2, 180);
    lv_obj_set_height(ui_ButtonTempS2, 100);
    lv_obj_set_x(ui_ButtonTempS2, 95);
    lv_obj_set_y(ui_ButtonTempS2, -54);
    lv_obj_set_align(ui_ButtonTempS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTempS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTempS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTempS2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTempS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTempS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonTempS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonTempS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtomTempS2Text = lv_label_create(ui_ButtonTempS2);
    lv_obj_set_width(ui_ButtomTempS2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtomTempS2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtomTempS2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtomTempS2Text, "GRAFICA\nSECTOR 2");
    lv_obj_set_style_text_color(ui_ButtomTempS2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtomTempS2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtomTempS2Text, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBalanceDiarioS1 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_ButtonBalanceDiarioS1, 180);
    lv_obj_set_height(ui_ButtonBalanceDiarioS1, 100);
    lv_obj_set_x(ui_ButtonBalanceDiarioS1, -97);
    lv_obj_set_y(ui_ButtonBalanceDiarioS1, 55);
    lv_obj_set_align(ui_ButtonBalanceDiarioS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBalanceDiarioS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBalanceDiarioS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonBalanceDiarioS1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBalanceDiarioS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBalanceDiarioS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonBalanceDiarioS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonBalanceDiarioS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceDiarioS1Text = lv_label_create(ui_ButtonBalanceDiarioS1);
    lv_obj_set_width(ui_BalanceDiarioS1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceDiarioS1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BalanceDiarioS1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BalanceDiarioS1Text, "BALANCE \nDIARIO \nSECTOR 1");
    lv_obj_set_style_text_color(ui_BalanceDiarioS1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceDiarioS1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceDiarioS1Text, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBalanceDIarioS2 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_ButtonBalanceDIarioS2, 180);
    lv_obj_set_height(ui_ButtonBalanceDIarioS2, 100);
    lv_obj_set_x(ui_ButtonBalanceDIarioS2, 95);
    lv_obj_set_y(ui_ButtonBalanceDIarioS2, 55);
    lv_obj_set_align(ui_ButtonBalanceDIarioS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBalanceDIarioS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBalanceDIarioS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonBalanceDIarioS2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBalanceDIarioS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBalanceDIarioS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonBalanceDIarioS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonBalanceDIarioS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceDiarioS2Text = lv_label_create(ui_ButtonBalanceDIarioS2);
    lv_obj_set_width(ui_BalanceDiarioS2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BalanceDiarioS2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BalanceDiarioS2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BalanceDiarioS2Text, "BALANCE \nDIARIO\nSECTOR 2");
    lv_obj_set_style_text_color(ui_BalanceDiarioS2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceDiarioS2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceDiarioS2Text, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuButtomRa4, ui_event_MenuButtomRa4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTempS1, ui_event_ButtonTempS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTempS2, ui_event_ButtonTempS2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBalanceDiarioS1, ui_event_ButtonBalanceDiarioS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBalanceDIarioS2, ui_event_ButtonBalanceDIarioS2, LV_EVENT_ALL, NULL);

}
