// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_GraficaTempHumS2_screen_init(void)
{
    ui_GraficaTempHumS2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GraficaTempHumS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GraficaTempHumS2, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GraficaTempHumS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa4 = lv_button_create(ui_GraficaTempHumS2);
    lv_obj_set_width(ui_BackButtomRa4, 195);
    lv_obj_set_height(ui_BackButtomRa4, 53);
    lv_obj_set_x(ui_BackButtomRa4, 0);
    lv_obj_set_y(ui_BackButtomRa4, -129);
    lv_obj_set_align(ui_BackButtomRa4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa4, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText4 = lv_label_create(ui_BackButtomRa4);
    lv_obj_set_width(ui_BackText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText4, "BACK");
    lv_obj_set_style_text_color(ui_BackText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_GraficaTempHumS2);
    lv_obj_set_width(ui_Chart2, 413);
    lv_obj_set_height(ui_Chart2, 229);
    lv_obj_set_x(ui_Chart2, -1);
    lv_obj_set_y(ui_Chart2, 19);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 48);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, -10, 60);

    ui_Chart2_Xaxis = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart2_Xaxis, 0, 24 > 0 ? 24 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart2_Xaxis, (24 > 0 ? 24 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis1 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart2_Yaxis1,  -10, 60);
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis1, (15 > 0 ? 15 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis2 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis2, (10 > 0 ? 10 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x00D93A),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_chart_series_t * ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xFF00A3),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 60 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Panel16 = lv_obj_create(ui_GraficaTempHumS2);
    lv_obj_set_width(ui_Panel16, 118);
    lv_obj_set_height(ui_Panel16, 50);
    lv_obj_set_x(ui_Panel16, -177);
    lv_obj_set_y(ui_Panel16, -125);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temptext1 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_temptext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temptext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temptext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temptext1, "TEMPERATURA");
    lv_obj_set_style_text_color(ui_temptext1, lv_color_hex(0x00D93A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temptext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temptext1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_GraficaTempHumS2);
    lv_obj_set_width(ui_Panel17, 118);
    lv_obj_set_height(ui_Panel17, 50);
    lv_obj_set_x(ui_Panel17, 174);
    lv_obj_set_y(ui_Panel17, -125);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humText1 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_humText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humText1, "HUMEDAD");
    lv_obj_set_style_text_color(ui_humText1, lv_color_hex(0xFF00A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humText1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackButtomRa4, ui_event_BackButtomRa4, LV_EVENT_ALL, NULL);

}
