// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Menu_Inicio_screen_init(void)
{
    ui_Menu_Inicio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Menu_Inicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Menu_Inicio, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu_Inicio, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Inicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Menu_Inicio);
    lv_obj_set_width(ui_Panel3, 210);
    lv_obj_set_height(ui_Panel3, 298);
    lv_obj_set_x(ui_Panel3, -115);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAmbiente = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_ButtonAmbiente, 183);
    lv_obj_set_height(ui_ButtonAmbiente, 117);
    lv_obj_set_x(ui_ButtonAmbiente, 0);
    lv_obj_set_y(ui_ButtonAmbiente, -65);
    lv_obj_set_align(ui_ButtonAmbiente, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAmbiente, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonAmbiente, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonAmbiente, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAmbiente, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAmbiente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonAmbiente, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonAmbiente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonAmbiente, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonAmbiente, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonAmbiente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ambientetext = lv_label_create(ui_ButtonAmbiente);
    lv_obj_set_width(ui_ambientetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ambientetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ambientetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ambientetext, "AMBIENTE");
    lv_obj_set_style_text_font(ui_ambientetext, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSuelo = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_ButtonSuelo, 183);
    lv_obj_set_height(ui_ButtonSuelo, 117);
    lv_obj_set_x(ui_ButtonSuelo, 1);
    lv_obj_set_y(ui_ButtonSuelo, 66);
    lv_obj_set_align(ui_ButtonSuelo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSuelo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonSuelo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSuelo, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSuelo, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonSuelo, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonSuelo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonSuelo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_suelotext = lv_label_create(ui_ButtonSuelo);
    lv_obj_set_width(ui_suelotext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_suelotext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_suelotext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_suelotext, "SUELO");
    lv_obj_set_style_text_font(ui_suelotext, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Menu_Inicio);
    lv_obj_set_width(ui_Panel4, 210);
    lv_obj_set_height(ui_Panel4, 146);
    lv_obj_set_x(ui_Panel4, 118);
    lv_obj_set_y(ui_Panel4, -73);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGraficas = lv_button_create(ui_Panel4);
    lv_obj_set_width(ui_ButtonGraficas, 183);
    lv_obj_set_height(ui_ButtonGraficas, 117);
    lv_obj_set_align(ui_ButtonGraficas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGraficas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonGraficas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonGraficas, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGraficas, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGraficas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonGraficas, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonGraficas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonGraficas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonGraficas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonGraficas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graficasname = lv_label_create(ui_ButtonGraficas);
    lv_obj_set_width(ui_graficasname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graficasname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_graficasname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graficasname, "DATOS");
    lv_obj_set_style_text_font(ui_graficasname, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Menu_Inicio);
    lv_obj_set_width(ui_Panel5, 210);
    lv_obj_set_height(ui_Panel5, 142);
    lv_obj_set_x(ui_Panel5, 120);
    lv_obj_set_y(ui_Panel5, 76);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfig = lv_button_create(ui_Panel5);
    lv_obj_set_width(ui_ButtonConfig, 183);
    lv_obj_set_height(ui_ButtonConfig, 117);
    lv_obj_set_align(ui_ButtonConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonConfig, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonConfig, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonConfig, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonConfig, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigName = lv_label_create(ui_ButtonConfig);
    lv_obj_set_width(ui_ConfigName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfigName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigName, "AJUSTES");
    lv_obj_set_style_text_font(ui_ConfigName, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonAmbiente, ui_event_ButtonAmbiente, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSuelo, ui_event_ButtonSuelo, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_ButtonGraficas, ui_event_ButtonGraficas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonConfig, ui_event_ButtonConfig, LV_EVENT_ALL, NULL);

}
