// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
//#include "../../managed_components/lvgl__lvgl/src/misc/lv_timer.h"
#include "core/lv_obj.h"
#include "misc/lv_event.h"
#include "misc/lv_timer_private.h"


void ui_Nebulizar_screen_init(void)
{
    ui_Nebulizar = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Nebulizar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Nebulizar, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Nebulizar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtom = lv_button_create(ui_Nebulizar);
    lv_obj_set_width(ui_MenuButtom, 100);
    lv_obj_set_height(ui_MenuButtom, 100);
    lv_obj_set_x(ui_MenuButtom, -175);
    lv_obj_set_y(ui_MenuButtom, -101);
    lv_obj_set_align(ui_MenuButtom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtom, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtom, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtom, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuButtom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuButtom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menutextconf = lv_label_create(ui_MenuButtom);
    lv_obj_set_width(ui_menutextconf, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutextconf, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menutextconf, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menutextconf, "MENU");
    lv_obj_set_style_text_font(ui_menutextconf, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NEBULIZAR_SECTOR2 = lv_switch_create(ui_Nebulizar);
    lv_obj_set_width(ui_NEBULIZAR_SECTOR2, 261);
    lv_obj_set_height(ui_NEBULIZAR_SECTOR2, 80);
    lv_obj_set_x(ui_NEBULIZAR_SECTOR2, 79);
    lv_obj_set_y(ui_NEBULIZAR_SECTOR2, 104);
    lv_obj_set_align(ui_NEBULIZAR_SECTOR2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NEBULIZAR_SECTOR2, LV_OBJ_FLAG_CHECKABLE);

   // lv_obj_set_style_bg_image_recolor(ui_NEBULIZAR_SECTOR1, lv_color_hex(0x003F5C), LV_PART_KNOB | LV_STATE_DEFAULT);
  //  lv_obj_set_style_bg_image_recolor_opa(ui_NEBULIZAR_SECTOR1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NEBULIZAR_SECTOR1 = lv_switch_create(ui_Nebulizar);
    lv_obj_set_width(ui_NEBULIZAR_SECTOR1, 261);
    lv_obj_set_height(ui_NEBULIZAR_SECTOR1, 80);
    lv_obj_set_x(ui_NEBULIZAR_SECTOR1, 80);
    lv_obj_set_y(ui_NEBULIZAR_SECTOR1, -45);
    lv_obj_set_align(ui_NEBULIZAR_SECTOR1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NEBULIZAR_SECTOR1, LV_OBJ_FLAG_CHECKABLE);//

   // lv_obj_set_style_bg_image_recolor(ui_NEBULIZAR_SECTOR2, lv_color_hex(0x003F5C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
   // lv_obj_set_style_bg_image_recolor_opa(ui_NEBULIZAR_SECTOR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_S1NEB = lv_obj_create(ui_Nebulizar);
    lv_obj_set_width(ui_S1NEB, 261);
    lv_obj_set_height(ui_S1NEB, 56);
    lv_obj_set_x(ui_S1NEB, 78);
    lv_obj_set_y(ui_S1NEB, -119);
    lv_obj_set_align(ui_S1NEB, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_S1NEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S1NEB, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S1NEB, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1NEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S1NEB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S1NEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Nebulizar);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 77);
    lv_obj_set_y(ui_Label2, -119);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SECTOR 1");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2NEB = lv_obj_create(ui_Nebulizar);
    lv_obj_set_width(ui_S2NEB, 261);
    lv_obj_set_height(ui_S2NEB, 56);
    lv_obj_set_x(ui_S2NEB, 78);
    lv_obj_set_y(ui_S2NEB, 30);
    lv_obj_set_align(ui_S2NEB, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_S2NEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S2NEB, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S2NEB, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S2NEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S2NEB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S2NEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Nebulizar);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 77);
    lv_obj_set_y(ui_Label4, 29);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SECTOR 2");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomNeb = lv_button_create(ui_Nebulizar);
    lv_obj_set_width(ui_BackButtomNeb, 100);
    lv_obj_set_height(ui_BackButtomNeb, 100);
    lv_obj_set_x(ui_BackButtomNeb, -175);
    lv_obj_set_y(ui_BackButtomNeb, 80);
    lv_obj_set_align(ui_BackButtomNeb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomNeb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomNeb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomNeb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomNeb, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomNeb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButtomNeb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackButtomNeb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomNeb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomNeb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomText = lv_label_create(ui_BackButtomNeb);
    lv_obj_set_width(ui_BackButtomText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackButtomText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackButtomText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackButtomText, "BACK");
    lv_obj_set_style_text_font(ui_BackButtomText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuButtom, ui_event_MenuButtom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButtomNeb, ui_event_BackButtomNeb, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_NEBULIZAR_SECTOR1, ui_event_ActivarNebulizacionS1, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_NEBULIZAR_SECTOR2, ui_event_ActivarNebulizacionS2, LV_EVENT_PRESSED, NULL);
    

}
