// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "font/lv_font.h"

void ui_RANGOSDPVS1MIN_screen_init(void)
{
    ui_RANGOSDPVS1MIN = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RANGOSDPVS1MIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RANGOSDPVS1MIN, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RANGOSDPVS1MIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa2 = lv_button_create(ui_RANGOSDPVS1MIN);
    lv_obj_set_width(ui_BackButtomRa2, 100);
    lv_obj_set_height(ui_BackButtomRa2, 59);
    lv_obj_set_x(ui_BackButtomRa2, -174);
    lv_obj_set_y(ui_BackButtomRa2, -130);
    lv_obj_set_align(ui_BackButtomRa2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText2 = lv_label_create(ui_BackButtomRa2);
    lv_obj_set_width(ui_BackText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText2, "BACK");
    lv_obj_set_style_text_color(ui_BackText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa3 = lv_button_create(ui_RANGOSDPVS1MIN);
    lv_obj_set_width(ui_MenuButtomRa3, 100);
    lv_obj_set_height(ui_MenuButtomRa3, 59);
    lv_obj_set_x(ui_MenuButtomRa3, 175);
    lv_obj_set_y(ui_MenuButtomRa3, -130);
    lv_obj_set_align(ui_MenuButtomRa3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa3, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_MenuButtomRa3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MENU");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_RANGOSDPVS1MIN);
    lv_obj_set_width(ui_Panel10, 442);
    lv_obj_set_height(ui_Panel10, 232);
    lv_obj_set_x(ui_Panel10, -1);
    lv_obj_set_y(ui_Panel10, 36);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsignaDPVMinTextS1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_ConsignaDPVMinTextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsignaDPVMinTextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsignaDPVMinTextS1, 0);
    lv_obj_set_y(ui_ConsignaDPVMinTextS1, -15);
    lv_obj_set_align(ui_ConsignaDPVMinTextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsignaDPVMinTextS1, "");
    lv_obj_set_style_text_color(ui_ConsignaDPVMinTextS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsignaDPVMinTextS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsignaDPVMinTextS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVMINS1Text = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_DPVMINS1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVMINS1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPVMINS1Text, 0);
    lv_obj_set_y(ui_DPVMINS1Text, 86);
    lv_obj_set_align(ui_DPVMINS1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVMINS1Text, "DPV MINIMO\n    SECTOR 1");
    lv_obj_set_style_text_color(ui_DPVMINS1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPVMINS1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPVMINS1Text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDecreDPVminS1 = lv_button_create(ui_Panel10);
    lv_obj_set_width(ui_ButtonDecreDPVminS1, 80);
    lv_obj_set_height(ui_ButtonDecreDPVminS1, 80);
    lv_obj_set_x(ui_ButtonDecreDPVminS1, -150);
    lv_obj_set_y(ui_ButtonDecreDPVminS1, -3);
    lv_obj_set_align(ui_ButtonDecreDPVminS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDecreDPVminS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDecreDPVminS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDecreDPVminS1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDecreDPVminS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDecreDPVminS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonDecreDPVminS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonDecreDPVminS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ButtonDecreDPVminS1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -5);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "-");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIncreDPVminS1 = lv_button_create(ui_Panel10);
    lv_obj_set_width(ui_ButtonIncreDPVminS1, 80);
    lv_obj_set_height(ui_ButtonIncreDPVminS1, 80);
    lv_obj_set_x(ui_ButtonIncreDPVminS1, 149);
    lv_obj_set_y(ui_ButtonIncreDPVminS1, -2);
    lv_obj_set_align(ui_ButtonIncreDPVminS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIncreDPVminS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonIncreDPVminS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIncreDPVminS1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIncreDPVminS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIncreDPVminS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonIncreDPVminS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonIncreDPVminS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ButtonIncreDPVminS1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel7, 168);
    lv_obj_set_height(ui_Panel7, 132);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -19);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consignaDPVMinS1 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_consignaDPVMinS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_consignaDPVMinS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_consignaDPVMinS1, 0);
    lv_obj_set_y(ui_consignaDPVMinS1, -10);
    lv_obj_set_align(ui_consignaDPVMinS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_consignaDPVMinS1, consignasDPV.DPVminS1);
    lv_obj_set_style_text_color(ui_consignaDPVMinS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_consignaDPVMinS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_consignaDPVMinS1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 30);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "kPa");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_ButtonInfo = lv_button_create(ui_RANGOSDPVS1MIN);
    lv_obj_set_width(ui_ButtonInfo, 70);
    lv_obj_set_height(ui_ButtonInfo, 70);
    lv_obj_set_x(ui_ButtonInfo, 0);
    lv_obj_set_y(ui_ButtonInfo, -121);
    lv_obj_set_align(ui_ButtonInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo, lv_color_hex(0x30E65E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);*/
    //lv_obj_set_style_shadow_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_textINFO = lv_label_create(ui_ButtonInfo);
    lv_obj_set_width(ui_textINFO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textINFO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textINFO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textINFO, "?");
    lv_obj_set_style_text_color(ui_textINFO, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textINFO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textINFO, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);*/

    lv_obj_add_event_cb(ui_BackButtomRa2, ui_event_BackButtomRa2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuButtomRa3, ui_event_MenuButtomRa3, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_ButtonInfo, ui_event_ButtonInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonIncreDPVminS1, increment_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMinS1);
    lv_obj_add_event_cb(ui_ButtonDecreDPVminS1, decrement_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMinS1);

}
