// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "font/lv_font.h"

void ui_RANGOSDPVS2MAX_screen_init(void)
{
    ui_RANGOSDPVS2MAX = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RANGOSDPVS2MAX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RANGOSDPVS2MAX, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RANGOSDPVS2MAX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa6 = lv_button_create(ui_RANGOSDPVS2MAX);
    lv_obj_set_width(ui_BackButtomRa6, 100);
    lv_obj_set_height(ui_BackButtomRa6, 59);
    lv_obj_set_x(ui_BackButtomRa6, -174);
    lv_obj_set_y(ui_BackButtomRa6, -130);
    lv_obj_set_align(ui_BackButtomRa6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa6, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText6 = lv_label_create(ui_BackButtomRa6);
    lv_obj_set_width(ui_BackText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText6, "BACK");
    lv_obj_set_style_text_color(ui_BackText6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa5 = lv_button_create(ui_RANGOSDPVS2MAX);
    lv_obj_set_width(ui_MenuButtomRa5, 100);
    lv_obj_set_height(ui_MenuButtomRa5, 59);
    lv_obj_set_x(ui_MenuButtomRa5, 175);
    lv_obj_set_y(ui_MenuButtomRa5, -130);
    lv_obj_set_align(ui_MenuButtomRa5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa5, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_MenuButtomRa5);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "MENU");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_RANGOSDPVS2MAX);
    lv_obj_set_width(ui_Panel21, 442);
    lv_obj_set_height(ui_Panel21, 232);
    lv_obj_set_x(ui_Panel21, -1);
    lv_obj_set_y(ui_Panel21, 36);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsignaDPVMaxTextS2 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_ConsignaDPVMaxTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsignaDPVMaxTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsignaDPVMaxTextS2, 0);
    lv_obj_set_y(ui_ConsignaDPVMaxTextS2, -15);
    lv_obj_set_align(ui_ConsignaDPVMaxTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsignaDPVMaxTextS2, "");
    lv_obj_set_style_text_color(ui_ConsignaDPVMaxTextS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsignaDPVMaxTextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsignaDPVMaxTextS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVMAXS2Text = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_DPVMAXS2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVMAXS2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPVMAXS2Text, 0);
    lv_obj_set_y(ui_DPVMAXS2Text, 86);
    lv_obj_set_align(ui_DPVMAXS2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVMAXS2Text, "DPV MAXIMO\n    SECTOR 2");
    lv_obj_set_style_text_color(ui_DPVMAXS2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPVMAXS2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPVMAXS2Text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDecreDPVmaxS2 = lv_button_create(ui_Panel21);
    lv_obj_set_width(ui_ButtonDecreDPVmaxS2, 80);
    lv_obj_set_height(ui_ButtonDecreDPVmaxS2, 80);
    lv_obj_set_x(ui_ButtonDecreDPVmaxS2, -150);
    lv_obj_set_y(ui_ButtonDecreDPVmaxS2, -3);
    lv_obj_set_align(ui_ButtonDecreDPVmaxS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDecreDPVmaxS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDecreDPVmaxS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDecreDPVmaxS2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDecreDPVmaxS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDecreDPVmaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //shadow_color(ui_ButtonDecreDPVmaxS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonDecreDPVmaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_ButtonDecreDPVmaxS2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -5);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "-");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIncreDPVmaxS2 = lv_button_create(ui_Panel21);
    lv_obj_set_width(ui_ButtonIncreDPVmaxS2, 80);
    lv_obj_set_height(ui_ButtonIncreDPVmaxS2, 80);
    lv_obj_set_x(ui_ButtonIncreDPVmaxS2, 149);
    lv_obj_set_y(ui_ButtonIncreDPVmaxS2, -2);
    lv_obj_set_align(ui_ButtonIncreDPVmaxS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIncreDPVmaxS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonIncreDPVmaxS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIncreDPVmaxS2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIncreDPVmaxS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIncreDPVmaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonIncreDPVmaxS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonIncreDPVmaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ButtonIncreDPVmaxS2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "+");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel22, 168);
    lv_obj_set_height(ui_Panel22, 132);
    lv_obj_set_x(ui_Panel22, 0);
    lv_obj_set_y(ui_Panel22, -19);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel22, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consignaDPVMaxS2 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_consignaDPVMaxS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_consignaDPVMaxS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_consignaDPVMaxS2, 0);
    lv_obj_set_y(ui_consignaDPVMaxS2, -10);
    lv_obj_set_align(ui_consignaDPVMaxS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_consignaDPVMaxS2, consignasDPV.DPVmaxS2);
    lv_obj_set_style_text_color(ui_consignaDPVMaxS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_consignaDPVMaxS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_consignaDPVMaxS2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 30);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "kPa");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_ButtonInfo3 = lv_button_create(ui_RANGOSDPVS2MAX);
    lv_obj_set_width(ui_ButtonInfo3, 70);
    lv_obj_set_height(ui_ButtonInfo3, 70);
    lv_obj_set_x(ui_ButtonInfo3, 0);
    lv_obj_set_y(ui_ButtonInfo3, -121);
    lv_obj_set_align(ui_ButtonInfo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonInfo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo3, lv_color_hex(0x30E65E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);*/
    //lv_obj_set_style_shadow_color(ui_ButtonInfo3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonInfo3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

   /* ui_textINFO3 = lv_label_create(ui_ButtonInfo3);
    lv_obj_set_width(ui_textINFO3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textINFO3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textINFO3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textINFO3, "?");
    lv_obj_set_style_text_color(ui_textINFO3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textINFO3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textINFO3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);*/

    lv_obj_add_event_cb(ui_BackButtomRa6, ui_event_BackButtomRa6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuButtomRa5, ui_event_MenuButtomRa5, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_ButtonInfo3, ui_event_ButtonInfo3, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_ButtonIncreDPVmaxS2, increment_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMaxS2);
    lv_obj_add_event_cb(ui_ButtonDecreDPVmaxS2, decrement_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMaxS2);

}
