// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_RANGOSSectoresDPV_screen_init(void)
{
    ui_RANGOSSectoresDPV = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RANGOSSectoresDPV, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RANGOSSectoresDPV, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RANGOSSectoresDPV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa7 = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_BackButtomRa7, 100);
    lv_obj_set_height(ui_BackButtomRa7, 70);
    lv_obj_set_x(ui_BackButtomRa7, -174);
    lv_obj_set_y(ui_BackButtomRa7, -120);
    lv_obj_set_align(ui_BackButtomRa7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa7, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText7 = lv_label_create(ui_BackButtomRa7);
    lv_obj_set_width(ui_BackText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText7, "BACK");
    lv_obj_set_style_text_color(ui_BackText7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa9 = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_MenuButtomRa9, 100);
    lv_obj_set_height(ui_MenuButtomRa9, 70);
    lv_obj_set_x(ui_MenuButtomRa9, 175);
    lv_obj_set_y(ui_MenuButtomRa9, -120);
    lv_obj_set_align(ui_MenuButtomRa9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa9, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_MenuButtomRa9);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "MENU");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_Panel20, 465);
    lv_obj_set_height(ui_Panel20, 220);
    lv_obj_set_x(ui_Panel20, 0);
    lv_obj_set_y(ui_Panel20, 45);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sector1ConfigDPVmin = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_Sector1ConfigDPVmin, 183);
    lv_obj_set_height(ui_Sector1ConfigDPVmin, 85);
    lv_obj_set_x(ui_Sector1ConfigDPVmin, -114);
    lv_obj_set_y(ui_Sector1ConfigDPVmin, 0);
    lv_obj_set_align(ui_Sector1ConfigDPVmin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sector1ConfigDPVmin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Sector1ConfigDPVmin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Sector1ConfigDPVmin, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sector1ConfigDPVmin, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sector1ConfigDPVmin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_Sector1ConfigDPVmin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_Sector1ConfigDPVmin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVmintextS1 = lv_label_create(ui_Sector1ConfigDPVmin);
    lv_obj_set_width(ui_DPVmintextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVmintextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DPVmintextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVmintextS1, "DPV MIN.\nSECTOR 1");
    lv_obj_set_style_text_font(ui_DPVmintextS1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sector1ConfigDPVmax = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_Sector1ConfigDPVmax, 183);
    lv_obj_set_height(ui_Sector1ConfigDPVmax, 85);
    lv_obj_set_x(ui_Sector1ConfigDPVmax, 114);
    lv_obj_set_y(ui_Sector1ConfigDPVmax, 0);
    lv_obj_set_align(ui_Sector1ConfigDPVmax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sector1ConfigDPVmax, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Sector1ConfigDPVmax, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Sector1ConfigDPVmax, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sector1ConfigDPVmax, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sector1ConfigDPVmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_Sector1ConfigDPVmax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_Sector1ConfigDPVmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVmaxtextS1 = lv_label_create(ui_Sector1ConfigDPVmax);
    lv_obj_set_width(ui_DPVmaxtextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVmaxtextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DPVmaxtextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVmaxtextS1, "DPV MAX.\nSECTOR 1");
    lv_obj_set_style_text_font(ui_DPVmaxtextS1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sector2ConfigDPVmin = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_Sector2ConfigDPVmin, 183);
    lv_obj_set_height(ui_Sector2ConfigDPVmin, 85);
    lv_obj_set_x(ui_Sector2ConfigDPVmin, -114);
    lv_obj_set_y(ui_Sector2ConfigDPVmin, 100);
    lv_obj_set_align(ui_Sector2ConfigDPVmin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sector2ConfigDPVmin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Sector2ConfigDPVmin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Sector2ConfigDPVmin, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sector2ConfigDPVmin, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sector2ConfigDPVmin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_Sector2ConfigDPVmin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_Sector2ConfigDPVmin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVmintextS2 = lv_label_create(ui_Sector2ConfigDPVmin);
    lv_obj_set_width(ui_DPVmintextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVmintextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DPVmintextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVmintextS2, "DPV MIN.\nSECTOR 2");
    lv_obj_set_style_text_font(ui_DPVmintextS2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sector2ConfigDPVmax = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_Sector2ConfigDPVmax, 183);
    lv_obj_set_height(ui_Sector2ConfigDPVmax, 85);
    lv_obj_set_x(ui_Sector2ConfigDPVmax, 114);
    lv_obj_set_y(ui_Sector2ConfigDPVmax, 100);
    lv_obj_set_align(ui_Sector2ConfigDPVmax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sector2ConfigDPVmax, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Sector2ConfigDPVmax, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Sector2ConfigDPVmax, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sector2ConfigDPVmax, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sector2ConfigDPVmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_Sector2ConfigDPVmax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_Sector2ConfigDPVmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVmaxtextS2 = lv_label_create(ui_Sector2ConfigDPVmax);
    lv_obj_set_width(ui_DPVmaxtextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVmaxtextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DPVmaxtextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVmaxtextS2, "DPV MAX.\nSECTOR 2");
    lv_obj_set_style_text_font(ui_DPVmaxtextS2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	 ui_ButtonInfo = lv_button_create(ui_RANGOSSectoresDPV);
    lv_obj_set_width(ui_ButtonInfo, 70);
    lv_obj_set_height(ui_ButtonInfo, 70);
    lv_obj_set_x(ui_ButtonInfo, 0);
    lv_obj_set_y(ui_ButtonInfo, -121);
    lv_obj_set_align(ui_ButtonInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo, lv_color_hex(0x30E65E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textINFO = lv_label_create(ui_ButtonInfo);
    lv_obj_set_width(ui_textINFO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textINFO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textINFO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textINFO, "?");
    lv_obj_set_style_text_color(ui_textINFO, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textINFO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textINFO, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_add_event_cb(ui_BackButtomRa7, ui_event_BackButtomRa7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuButtomRa9, ui_event_MenuButtomRa9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sector1ConfigDPVmin, ui_event_Sector1ConfigDPVmin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sector1ConfigDPVmax, ui_event_Sector1ConfigDPVmax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sector2ConfigDPVmin, ui_event_Sector2ConfigDPVmin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sector2ConfigDPVmax, ui_event_Sector2ConfigDPVmax, LV_EVENT_ALL, NULL);
	lv_obj_add_event_cb(ui_ButtonInfo, ui_event_ButtonInfo, LV_EVENT_ALL, NULL);
}
