// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "font/lv_font.h"

void ui_RANGOSDPVS2MIN_screen_init(void)
{
    ui_RANGOSDPVS2MIN = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RANGOSDPVS2MIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RANGOSDPVS2MIN, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RANGOSDPVS2MIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa1 = lv_button_create(ui_RANGOSDPVS2MIN);
    lv_obj_set_width(ui_BackButtomRa1, 100);
    lv_obj_set_height(ui_BackButtomRa1, 59);
    lv_obj_set_x(ui_BackButtomRa1, -174);
    lv_obj_set_y(ui_BackButtomRa1, -130);
    lv_obj_set_align(ui_BackButtomRa1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText1 = lv_label_create(ui_BackButtomRa1);
    lv_obj_set_width(ui_BackText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText1, "BACK");
    lv_obj_set_style_text_color(ui_BackText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa1 = lv_button_create(ui_RANGOSDPVS2MIN);
    lv_obj_set_width(ui_MenuButtomRa1, 100);
    lv_obj_set_height(ui_MenuButtomRa1, 59);
    lv_obj_set_x(ui_MenuButtomRa1, 175);
    lv_obj_set_y(ui_MenuButtomRa1, -130);
    lv_obj_set_align(ui_MenuButtomRa1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_MenuButtomRa1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "MENU");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_RANGOSDPVS2MIN);
    lv_obj_set_width(ui_Panel8, 442);
    lv_obj_set_height(ui_Panel8, 232);
    lv_obj_set_x(ui_Panel8, -1);
    lv_obj_set_y(ui_Panel8, 36);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsignaDPVMinTextS2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_ConsignaDPVMinTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsignaDPVMinTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsignaDPVMinTextS2, 0);
    lv_obj_set_y(ui_ConsignaDPVMinTextS2, -15);
    lv_obj_set_align(ui_ConsignaDPVMinTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsignaDPVMinTextS2, "");
    lv_obj_set_style_text_color(ui_ConsignaDPVMinTextS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsignaDPVMinTextS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsignaDPVMinTextS2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVMINS2Text = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_DPVMINS2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVMINS2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPVMINS2Text, 0);
    lv_obj_set_y(ui_DPVMINS2Text, 86);
    lv_obj_set_align(ui_DPVMINS2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVMINS2Text, "DPV MINIMO\n    SECTOR 2");
    lv_obj_set_style_text_color(ui_DPVMINS2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPVMINS2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPVMINS2Text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDecreDPVminS2 = lv_button_create(ui_Panel8);
    lv_obj_set_width(ui_ButtonDecreDPVminS2, 80);
    lv_obj_set_height(ui_ButtonDecreDPVminS2, 80);
    lv_obj_set_x(ui_ButtonDecreDPVminS2, -150);
    lv_obj_set_y(ui_ButtonDecreDPVminS2, -3);
    lv_obj_set_align(ui_ButtonDecreDPVminS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDecreDPVminS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDecreDPVminS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDecreDPVminS2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDecreDPVminS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDecreDPVminS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonDecreDPVminS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonDecreDPVminS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ButtonDecreDPVminS2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, -5);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIncreDPVminS2 = lv_button_create(ui_Panel8);
    lv_obj_set_width(ui_ButtonIncreDPVminS2, 80);
    lv_obj_set_height(ui_ButtonIncreDPVminS2, 80);
    lv_obj_set_x(ui_ButtonIncreDPVminS2, 149);
    lv_obj_set_y(ui_ButtonIncreDPVminS2, -2);
    lv_obj_set_align(ui_ButtonIncreDPVminS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIncreDPVminS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonIncreDPVminS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIncreDPVminS2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIncreDPVminS2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIncreDPVminS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonIncreDPVminS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonIncreDPVminS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ButtonIncreDPVminS2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "+");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Panel9, 168);
    lv_obj_set_height(ui_Panel9, 132);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -19);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consignaDPVMinS2 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_consignaDPVMinS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_consignaDPVMinS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_consignaDPVMinS2, 0);
    lv_obj_set_y(ui_consignaDPVMinS2, -10);
    lv_obj_set_align(ui_consignaDPVMinS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_consignaDPVMinS2, consignasDPV.DPVminS2);
    lv_obj_set_style_text_color(ui_consignaDPVMinS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_consignaDPVMinS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_consignaDPVMinS2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, 30);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "kPa");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_ButtonInfo1 = lv_button_create(ui_RANGOSDPVS2MIN);
    lv_obj_set_width(ui_ButtonInfo1, 70);
    lv_obj_set_height(ui_ButtonInfo1, 70);
    lv_obj_set_x(ui_ButtonInfo1, 0);
    lv_obj_set_y(ui_ButtonInfo1, -121);
    lv_obj_set_align(ui_ButtonInfo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonInfo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo1, lv_color_hex(0x30E65E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);*/
    //lv_obj_set_style_shadow_color(ui_ButtonInfo1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonInfo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_textINFO1 = lv_label_create(ui_ButtonInfo1);
    lv_obj_set_width(ui_textINFO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textINFO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textINFO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textINFO1, "?");
    lv_obj_set_style_text_color(ui_textINFO1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textINFO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textINFO1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);*/

    lv_obj_add_event_cb(ui_BackButtomRa1, ui_event_BackButtomRa1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuButtomRa1, ui_event_MenuButtomRa1, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_ButtonInfo1, ui_event_ButtonInfo1, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_ButtonIncreDPVminS2, increment_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMinS2);
    lv_obj_add_event_cb(ui_ButtonDecreDPVminS2, decrement_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMinS2);

}
