// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "font/lv_font.h"

void ui_RANGOSDPVS1MAX_screen_init(void)
{
    ui_RANGOSDPVS1MAX = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RANGOSDPVS1MAX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RANGOSDPVS1MAX, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RANGOSDPVS1MAX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtomRa3 = lv_button_create(ui_RANGOSDPVS1MAX);
    lv_obj_set_width(ui_BackButtomRa3, 100);
    lv_obj_set_height(ui_BackButtomRa3, 59);
    lv_obj_set_x(ui_BackButtomRa3, -174);
    lv_obj_set_y(ui_BackButtomRa3, -130);
    lv_obj_set_align(ui_BackButtomRa3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtomRa3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButtomRa3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtomRa3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtomRa3, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtomRa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_BackButtomRa3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_BackButtomRa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText3 = lv_label_create(ui_BackButtomRa3);
    lv_obj_set_width(ui_BackText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText3, "BACK");
    lv_obj_set_style_text_color(ui_BackText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButtomRa2 = lv_button_create(ui_RANGOSDPVS1MAX);
    lv_obj_set_width(ui_MenuButtomRa2, 100);
    lv_obj_set_height(ui_MenuButtomRa2, 59);
    lv_obj_set_x(ui_MenuButtomRa2, 175);
    lv_obj_set_y(ui_MenuButtomRa2, -130);
    lv_obj_set_align(ui_MenuButtomRa2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuButtomRa2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButtomRa2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButtomRa2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButtomRa2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButtomRa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuButtomRa2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuButtomRa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_MenuButtomRa2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "MENU");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_RANGOSDPVS1MAX);
    lv_obj_set_width(ui_Panel13, 442);
    lv_obj_set_height(ui_Panel13, 232);
    lv_obj_set_x(ui_Panel13, -1);
    lv_obj_set_y(ui_Panel13, 36);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsignaDPVMaxTextS1 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_ConsignaDPVMaxTextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsignaDPVMaxTextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsignaDPVMaxTextS1, 0);
    lv_obj_set_y(ui_ConsignaDPVMaxTextS1, -15);
    lv_obj_set_align(ui_ConsignaDPVMaxTextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsignaDPVMaxTextS1, "");
    lv_obj_set_style_text_color(ui_ConsignaDPVMaxTextS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsignaDPVMaxTextS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsignaDPVMaxTextS1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DPVMAXS1Text = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_DPVMAXS1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DPVMAXS1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DPVMAXS1Text, 0);
    lv_obj_set_y(ui_DPVMAXS1Text, 86);
    lv_obj_set_align(ui_DPVMAXS1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DPVMAXS1Text, "DPV MAXIMO\n    SECTOR 1");
    lv_obj_set_style_text_color(ui_DPVMAXS1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DPVMAXS1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DPVMAXS1Text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDecreDPVmaxS1 = lv_button_create(ui_Panel13);
    lv_obj_set_width(ui_ButtonDecreDPVmaxS1, 80);
    lv_obj_set_height(ui_ButtonDecreDPVmaxS1, 80);
    lv_obj_set_x(ui_ButtonDecreDPVmaxS1, -150);
    lv_obj_set_y(ui_ButtonDecreDPVmaxS1, -3);
    lv_obj_set_align(ui_ButtonDecreDPVmaxS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDecreDPVmaxS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDecreDPVmaxS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDecreDPVmaxS1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDecreDPVmaxS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDecreDPVmaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonDecreDPVmaxS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonDecreDPVmaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ButtonDecreDPVmaxS1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -5);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "-");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIncreDPVmaxS1 = lv_button_create(ui_Panel13);
    lv_obj_set_width(ui_ButtonIncreDPVmaxS1, 80);
    lv_obj_set_height(ui_ButtonIncreDPVmaxS1, 80);
    lv_obj_set_x(ui_ButtonIncreDPVmaxS1, 149);
    lv_obj_set_y(ui_ButtonIncreDPVmaxS1, -2);
    lv_obj_set_align(ui_ButtonIncreDPVmaxS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIncreDPVmaxS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonIncreDPVmaxS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIncreDPVmaxS1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIncreDPVmaxS1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIncreDPVmaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonIncreDPVmaxS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonIncreDPVmaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_ButtonIncreDPVmaxS1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "+");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Panel13);
    lv_obj_set_width(ui_Panel14, 168);
    lv_obj_set_height(ui_Panel14, 132);
    lv_obj_set_x(ui_Panel14, 0);
    lv_obj_set_y(ui_Panel14, -19);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consignaDPVMaxS1 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_consignaDPVMaxS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_consignaDPVMaxS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_consignaDPVMaxS1, 0);
    lv_obj_set_y(ui_consignaDPVMaxS1, -10);
    lv_obj_set_align(ui_consignaDPVMaxS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_consignaDPVMaxS1, consignasDPV.DPVmaxS1);
    lv_obj_set_style_text_color(ui_consignaDPVMaxS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_consignaDPVMaxS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_consignaDPVMaxS1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 30);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "kPa");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_ButtonInfo2 = lv_button_create(ui_RANGOSDPVS1MAX);
    lv_obj_set_width(ui_ButtonInfo2, 70);
    lv_obj_set_height(ui_ButtonInfo2, 70);
    lv_obj_set_x(ui_ButtonInfo2, 0);
    lv_obj_set_y(ui_ButtonInfo2, -121);
    lv_obj_set_align(ui_ButtonInfo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonInfo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo2, lv_color_hex(0x30E65E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonInfo2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);*/
    //lv_obj_set_style_shadow_opa(ui_ButtonInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*ui_textINFO2 = lv_label_create(ui_ButtonInfo2);
    lv_obj_set_width(ui_textINFO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textINFO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textINFO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textINFO2, "?");
    lv_obj_set_style_text_color(ui_textINFO2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textINFO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textINFO2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);*/

    lv_obj_add_event_cb(ui_BackButtomRa3, ui_event_BackButtomRa3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuButtomRa2, ui_event_MenuButtomRa2, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_ButtonInfo2, ui_event_ButtonInfo2, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_ButtonIncreDPVmaxS1, increment_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMaxS1);
    lv_obj_add_event_cb(ui_ButtonDecreDPVmaxS1, decrement_event_handler, LV_EVENT_PRESSED, ui_consignaDPVMaxS1);

}
