// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SECTORES_screen_init(void)
{
    ui_SECTORES = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SECTORES, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SECTORES, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SECTORES, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMenu = lv_button_create(ui_SECTORES);
    lv_obj_set_width(ui_ButtonMenu, 100);
    lv_obj_set_height(ui_ButtonMenu, 100);
    lv_obj_set_x(ui_ButtonMenu, -175);
    lv_obj_set_y(ui_ButtonMenu, -101);
    lv_obj_set_align(ui_ButtonMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMenu, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMenu, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_ButtonMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_ButtonMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menutext = lv_label_create(ui_ButtonMenu);
    lv_obj_set_width(ui_menutext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menutext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menutext, "MENU");
    lv_obj_set_style_text_font(ui_menutext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SECTOR1 = lv_button_create(ui_SECTORES);
    lv_obj_set_width(ui_SECTOR1, 254);
    lv_obj_set_height(ui_SECTOR1, 68);
    lv_obj_set_x(ui_SECTOR1, 71);
    lv_obj_set_y(ui_SECTOR1, -79);
    lv_obj_set_align(ui_SECTOR1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SECTOR1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SECTOR1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SECTOR1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SECTOR1, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SECTOR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_SECTOR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_SECTOR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sector1text = lv_label_create(ui_SECTOR1);
    lv_obj_set_width(ui_sector1text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sector1text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sector1text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sector1text, "SECTOR 1");
    lv_obj_set_style_text_color(ui_sector1text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sector1text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sector1text, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SECTOR2 = lv_button_create(ui_SECTORES);
    lv_obj_set_width(ui_SECTOR2, 254);
    lv_obj_set_height(ui_SECTOR2, 68);
    lv_obj_set_x(ui_SECTOR2, 71);
    lv_obj_set_y(ui_SECTOR2, 41);
    lv_obj_set_align(ui_SECTOR2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SECTOR2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SECTOR2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SECTOR2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SECTOR2, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SECTOR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SECTOR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SECTOR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_SECTOR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_SECTOR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sector2text = lv_label_create(ui_SECTOR2);
    lv_obj_set_width(ui_sector2text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sector2text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sector2text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sector2text, "SECTOR 2");
    lv_obj_set_style_text_color(ui_sector2text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sector2text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sector2text, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonMenu, ui_event_ButtonMenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SECTOR1, ui_event_SECTOR1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SECTOR2, ui_event_SECTOR2, LV_EVENT_ALL, NULL);

}
