// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SUELO_screen_init(void)
{
    ui_SUELO = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SUELO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SUELO, lv_color_hex(0x7FD8E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SUELO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperaturaSuelo1 = lv_obj_create(ui_SUELO);
    lv_obj_set_width(ui_TemperaturaSuelo1, 225);
    lv_obj_set_height(ui_TemperaturaSuelo1, 120);
    lv_obj_set_x(ui_TemperaturaSuelo1, -116);
    lv_obj_set_y(ui_TemperaturaSuelo1, -37);
    lv_obj_set_align(ui_TemperaturaSuelo1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TemperaturaSuelo1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TemperaturaSuelo1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TemperaturaSuelo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TemperaturaSuelo1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperaturaSuelo1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperaturaSuelo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperaturaSuelo1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperaturaSuelo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barraTempSuelo = lv_bar_create(ui_TemperaturaSuelo1);
    lv_bar_set_range(ui_barraTempSuelo, -10, 75);
    lv_obj_set_width(ui_barraTempSuelo, 186);
    lv_obj_set_height(ui_barraTempSuelo, 10);
    lv_obj_set_x(ui_barraTempSuelo, -97);
    lv_obj_set_y(ui_barraTempSuelo, -18);
    lv_obj_set_align(ui_barraTempSuelo, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barraTempSuelo, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barraTempSuelo,
                                                                                                     lv_obj_get_style_pad_right(ui_barraTempSuelo, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_MenuBotonSoil = lv_button_create(ui_SUELO);
    lv_obj_set_width(ui_MenuBotonSoil, 100);
    lv_obj_set_height(ui_MenuBotonSoil, 59);
    lv_obj_set_x(ui_MenuBotonSoil, 0);
    lv_obj_set_y(ui_MenuBotonSoil, -130);
    lv_obj_set_align(ui_MenuBotonSoil, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuBotonSoil, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuBotonSoil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuBotonSoil, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuBotonSoil, lv_color_hex(0x003F5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuBotonSoil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuBotonSoil, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuBotonSoil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_color(ui_MenuBotonSoil, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_shadow_opa(ui_MenuBotonSoil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menutext3 = lv_label_create(ui_MenuBotonSoil);
    lv_obj_set_width(ui_menutext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menutext3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menutext3, "MENU");
    lv_obj_set_style_text_font(ui_menutext3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -117);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TEMPERATURA");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HUMEDADSUELO1 = lv_obj_create(ui_SUELO);
    lv_obj_set_width(ui_HUMEDADSUELO1, 225);
    lv_obj_set_height(ui_HUMEDADSUELO1, 120);
    lv_obj_set_x(ui_HUMEDADSUELO1, 115);
    lv_obj_set_y(ui_HUMEDADSUELO1, -37);
    lv_obj_set_align(ui_HUMEDADSUELO1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HUMEDADSUELO1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HUMEDADSUELO1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_HUMEDADSUELO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HUMEDADSUELO1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HUMEDADSUELO1, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HUMEDADSUELO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HUMEDADSUELO1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HUMEDADSUELO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barraHumSuelo = lv_bar_create(ui_HUMEDADSUELO1);
    lv_obj_set_width(ui_barraHumSuelo, 186);
    lv_obj_set_height(ui_barraHumSuelo, 10);
    lv_obj_set_x(ui_barraHumSuelo, 113);
    lv_obj_set_y(ui_barraHumSuelo, -72);
    lv_obj_set_align(ui_barraHumSuelo, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barraHumSuelo, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barraHumSuelo,
                                                                                                    lv_obj_get_style_pad_right(ui_barraHumSuelo, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_CONDUCTIVIDAD = lv_obj_create(ui_SUELO);
    lv_obj_set_width(ui_CONDUCTIVIDAD, 225);
    lv_obj_set_height(ui_CONDUCTIVIDAD, 120);
    lv_obj_set_x(ui_CONDUCTIVIDAD, -115);
    lv_obj_set_y(ui_CONDUCTIVIDAD, 90);
    lv_obj_set_align(ui_CONDUCTIVIDAD, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CONDUCTIVIDAD, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CONDUCTIVIDAD, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_CONDUCTIVIDAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CONDUCTIVIDAD, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CONDUCTIVIDAD, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONDUCTIVIDAD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CONDUCTIVIDAD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CONDUCTIVIDAD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barraConducSuelo = lv_bar_create(ui_CONDUCTIVIDAD);
    lv_bar_set_range(ui_barraConducSuelo, 0, 10);
    lv_obj_set_width(ui_barraConducSuelo, 186);
    lv_obj_set_height(ui_barraConducSuelo, 10);
    lv_obj_set_x(ui_barraConducSuelo, -112);
    lv_obj_set_y(ui_barraConducSuelo, 88);
    lv_obj_set_align(ui_barraConducSuelo, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barraConducSuelo, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barraConducSuelo,
                                                                                                       lv_obj_get_style_pad_right(ui_barraConducSuelo, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_PPPPHHH = lv_obj_create(ui_SUELO);
    lv_obj_set_width(ui_PPPPHHH, 225);
    lv_obj_set_height(ui_PPPPHHH, 120);
    lv_obj_set_x(ui_PPPPHHH, 117);
    lv_obj_set_y(ui_PPPPHHH, 90);
    lv_obj_set_align(ui_PPPPHHH, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PPPPHHH, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PPPPHHH, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PPPPHHH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PPPPHHH, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PPPPHHH, lv_color_hex(0x494847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PPPPHHH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PPPPHHH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PPPPHHH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barrPHSuelo = lv_bar_create(ui_PPPPHHH);
    lv_bar_set_range(ui_barrPHSuelo, 0, 10);
    lv_obj_set_width(ui_barrPHSuelo, 186);
    lv_obj_set_height(ui_barrPHSuelo, 10);
    lv_obj_set_x(ui_barrPHSuelo, 143);
    lv_obj_set_y(ui_barrPHSuelo, 84);
    lv_obj_set_align(ui_barrPHSuelo, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barrPHSuelo, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barrPHSuelo,
                                                                                                  lv_obj_get_style_pad_right(ui_barrPHSuelo, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_humsuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_humsuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humsuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humsuelo, 115);
    lv_obj_set_y(ui_humsuelo, 2);
    lv_obj_set_align(ui_humsuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humsuelo, "HUMEDAD");
    lv_obj_set_style_text_color(ui_humsuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humsuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humsuelo, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conducsuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_conducsuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_conducsuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_conducsuelo, -116);
    lv_obj_set_y(ui_conducsuelo, 127);
    lv_obj_set_align(ui_conducsuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_conducsuelo, "CONDUCTIVIDAD");
    lv_obj_set_style_text_color(ui_conducsuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_conducsuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_conducsuelo, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_phsuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_phsuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phsuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phsuelo, 119);
    lv_obj_set_y(ui_phsuelo, 128);
    lv_obj_set_align(ui_phsuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_phsuelo, "PH");
    lv_obj_set_style_text_color(ui_phsuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_phsuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_phsuelo, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORtempSuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_VALORtempSuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORtempSuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORtempSuelo, -114);
    lv_obj_set_y(ui_VALORtempSuelo, -37);
    lv_obj_set_align(ui_VALORtempSuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORtempSuelo, SoilData1.temp);
    lv_obj_set_style_text_color(ui_VALORtempSuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORtempSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORtempSuelo, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORhumSuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_VALORhumSuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORhumSuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORhumSuelo, 115);
    lv_obj_set_y(ui_VALORhumSuelo, -37);
    lv_obj_set_align(ui_VALORhumSuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORhumSuelo, SoilData1.hum);
    lv_obj_set_style_text_color(ui_VALORhumSuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORhumSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORhumSuelo, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORConducSuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_VALORConducSuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORConducSuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORConducSuelo, -114);
    lv_obj_set_y(ui_VALORConducSuelo, 86);
    lv_obj_set_align(ui_VALORConducSuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORConducSuelo, SoilData1.conduc);
    lv_obj_set_style_text_color(ui_VALORConducSuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORConducSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORConducSuelo, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VALORPHSuelo = lv_label_create(ui_SUELO);
    lv_obj_set_width(ui_VALORPHSuelo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALORPHSuelo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALORPHSuelo, 115);
    lv_obj_set_y(ui_VALORPHSuelo, 86);
    lv_obj_set_align(ui_VALORPHSuelo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALORPHSuelo, SoilData1.ph);
    lv_obj_set_style_text_color(ui_VALORPHSuelo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALORPHSuelo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALORPHSuelo, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuBotonSoil, ui_event_MenuBotonSoil, LV_EVENT_ALL, NULL);

}
