// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "core/lv_obj.h"
#include "esp_log.h"
#include "misc/lv_event.h"
#include "ui_helpers.h"
#include <stdio.h>



//
SensorAmbData SectorS1Amb = {0};
SensorAmbData SectorS2Amb = {0};

SoilData SoilData1 = {0};

/*int graficaS1[N][N] = {0};
int graficaS2[N][N] = {0};

Balances BalancesS1 = {0};
Balances BalancesS2 = {0};*/

ConsignasDPV consignasDPV = {0};

TipoConsigna consigna_screen = {0};


//
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Menu_Inicio
void ui_Menu_Inicio_screen_init(void);
lv_obj_t * ui_Menu_Inicio;
lv_obj_t * ui_Panel3;
void ui_event_ButtonAmbiente(lv_event_t * e);
lv_obj_t * ui_ButtonAmbiente;
lv_obj_t * ui_ambientetext;
void ui_event_ButtonSuelo(lv_event_t * e);
lv_obj_t * ui_ButtonSuelo;
lv_obj_t * ui_suelotext;
lv_obj_t * ui_Panel4;
void ui_event_ButtonGraficas(lv_event_t * e);
lv_obj_t * ui_ButtonGraficas;
lv_obj_t * ui_graficasname;
lv_obj_t * ui_Panel5;
void ui_event_ButtonConfig(lv_event_t * e);
lv_obj_t * ui_ButtonConfig;
lv_obj_t * ui_ConfigName;
// CUSTOM VARIABLES

// SCREEN: ui_AMBIENTES1
void ui_AMBIENTES1_screen_init(void);
lv_obj_t * ui_AMBIENTES1;
lv_obj_t * ui_TEMPERATURA1;
lv_obj_t * ui_temperaturaindicator1;
lv_obj_t * ui_HUMEDAD1;
lv_obj_t * ui_humedadindicator1;
void ui_event_botonmenu1(lv_event_t * e);
lv_obj_t * ui_botonmenu1;
lv_obj_t * ui_menutext1;
lv_obj_t * ui_humedadtext;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_botonbacktext;
lv_obj_t * ui_temperatura1text;
lv_obj_t * ui_VALORtempS1;
lv_obj_t * ui_VALORhumS1;
lv_obj_t * ui_PanelDPVS1;
lv_obj_t * ui_DPV1text;
lv_obj_t * ui_VALORDPVS1;
// CUSTOM VARIABLES

// SCREEN: ui_SUELO
void ui_SUELO_screen_init(void);
lv_obj_t * ui_SUELO;
lv_obj_t * ui_TemperaturaSuelo1;
lv_obj_t * ui_barraTempSuelo;
void ui_event_MenuBotonSoil(lv_event_t * e);
lv_obj_t * ui_MenuBotonSoil;
lv_obj_t * ui_menutext3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_HUMEDADSUELO1;
lv_obj_t * ui_barraHumSuelo;
lv_obj_t * ui_CONDUCTIVIDAD;
lv_obj_t * ui_barraConducSuelo;
lv_obj_t * ui_PPPPHHH;
lv_obj_t * ui_barrPHSuelo;
lv_obj_t * ui_humsuelo;
lv_obj_t * ui_conducsuelo;
lv_obj_t * ui_phsuelo;
lv_obj_t * ui_VALORtempSuelo;
lv_obj_t * ui_VALORhumSuelo;
lv_obj_t * ui_VALORConducSuelo;
lv_obj_t * ui_VALORPHSuelo;
// CUSTOM VARIABLES

// SCREEN: ui_SECTORES
void ui_SECTORES_screen_init(void);
lv_obj_t * ui_SECTORES;
void ui_event_ButtonMenu(lv_event_t * e);
lv_obj_t * ui_ButtonMenu;
lv_obj_t * ui_menutext;
void ui_event_SECTOR1(lv_event_t * e);
lv_obj_t * ui_SECTOR1;
lv_obj_t * ui_sector1text;
void ui_event_SECTOR2(lv_event_t * e);
lv_obj_t * ui_SECTOR2;
lv_obj_t * ui_sector2text;
// CUSTOM VARIABLES

// SCREEN: ui_AMBIENTES2
void ui_AMBIENTES2_screen_init(void);
lv_obj_t * ui_AMBIENTES2;
void ui_event_MenuButton(lv_event_t * e);
lv_obj_t * ui_MenuButton;
lv_obj_t * ui_Label9;
lv_obj_t * ui_TEMPERATURAS2;
lv_obj_t * ui_tamperaturaindicator2;
lv_obj_t * ui_HUMEDADS2;
lv_obj_t * ui_humedadindicator2;
lv_obj_t * ui_temperaturatext2;
lv_obj_t * ui_humedadtext2;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_Label11;
lv_obj_t * ui_VALORtempS2;
lv_obj_t * ui_VALORhumS2;
lv_obj_t * ui_PanelDPVS2;
lv_obj_t * ui_DPV2text;
lv_obj_t * ui_VALORDPVS2;
// CUSTOM VARIABLES

// SCREEN: ui_Nebulizar
void ui_Nebulizar_screen_init(void);
lv_obj_t * ui_Nebulizar;
void ui_event_MenuButtom(lv_event_t * e);
lv_obj_t * ui_MenuButtom;
lv_obj_t * ui_menutextconf;
lv_obj_t * ui_NEBULIZAR_SECTOR1;
lv_obj_t * ui_NEBULIZAR_SECTOR2;
lv_obj_t * ui_S1NEB;
lv_obj_t * ui_Label2;
lv_obj_t * ui_S2NEB;
lv_obj_t * ui_Label4;
void ui_event_BackButtomNeb(lv_event_t * e);
lv_obj_t * ui_BackButtomNeb;
lv_obj_t * ui_BackButtomText;
// CUSTOM VARIABLES

// SCREEN: ui_CONFIGURACION
void ui_CONFIGURACION_screen_init(void);
lv_obj_t * ui_CONFIGURACION;
lv_obj_t * ui_Panel1;
void ui_event_ButtonNebulizar(lv_event_t * e);
lv_obj_t * ui_ButtonNebulizar;
lv_obj_t * ui_Nebulizartext;
lv_obj_t * ui_Panel2;
void ui_event_ButtonRangos(lv_event_t * e);
lv_obj_t * ui_ButtonRangos;
lv_obj_t * ui_RANGOStext;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_SwitchDesactivarAutomatismo;

lv_obj_t * ui_Label14;
void ui_event_ButtonMenu2(lv_event_t * e);
lv_obj_t * ui_ButtonMenu2;
void ui_event_MENUText2(lv_event_t * e);
lv_obj_t * ui_MENUText2;
// CUSTOM VARIABLES



// SCREEN: ui_GraficasAmbiente
void ui_GraficasAmbiente_screen_init(void);
lv_obj_t * ui_GraficasAmbiente;
void ui_event_MenuButtomRa4(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa4;
lv_obj_t * ui_menutext6;
lv_obj_t * ui_Panel11;
void ui_event_ButtonTempS1(lv_event_t * e);
lv_obj_t * ui_ButtonTempS1;
lv_obj_t * ui_ButtomTempS1Text;
void ui_event_ButtonTempS2(lv_event_t * e);
lv_obj_t * ui_ButtonTempS2;
lv_obj_t * ui_ButtomTempS2Text;
void ui_event_ButtonBalanceDiarioS1(lv_event_t * e);
lv_obj_t * ui_ButtonBalanceDiarioS1;
lv_obj_t * ui_BalanceDiarioS1Text;
void ui_event_ButtonBalanceDIarioS2(lv_event_t * e);
lv_obj_t * ui_ButtonBalanceDIarioS2;
lv_obj_t * ui_BalanceDiarioS2Text;
// CUSTOM VARIABLES

// SCREEN: ui_GraficaTempHumS1
void ui_GraficaTempHumS1_screen_init(void);
lv_obj_t * ui_GraficaTempHumS1;
void ui_event_BackButtomRa5(lv_event_t * e);
lv_obj_t * ui_BackButtomRa5;
lv_obj_t * ui_BackText5;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart1_Xaxis;
lv_obj_t * ui_Chart1_Yaxis1;
lv_obj_t * ui_Chart1_Yaxis2;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_temptext;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_humText;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenINFODPV
void ui_ScreenINFODPV_screen_init(void);
lv_obj_t * ui_ScreenINFODPV;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Label32;
void ui_event_ButtonBack(lv_event_t * e);
lv_obj_t * ui_ButtonBack;
lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

// SCREEN: ui_GraficaTempHumS2
void ui_GraficaTempHumS2_screen_init(void);
lv_obj_t * ui_GraficaTempHumS2;
void ui_event_BackButtomRa4(lv_event_t * e);
lv_obj_t * ui_BackButtomRa4;
lv_obj_t * ui_BackText4;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Chart2_Xaxis;
lv_obj_t * ui_Chart2_Yaxis1;
lv_obj_t * ui_Chart2_Yaxis2;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_temptext1;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_humText1;
// CUSTOM VARIABLES



// SCREEN: ui_BalanceDiarioS1
void ui_BalanceDiarioS1_screen_init(void);
lv_obj_t * ui_BalanceDiarioS1;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_BalanceTempTextMinS1;
lv_obj_t * ui_TextTempMinimaS1;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_BalanceTempTextMaxS1;
lv_obj_t * ui_TextTempMaximaS1;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_BalanceHumTextMinS1;
lv_obj_t * ui_TextHumMinimaS1;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_BalanceHumMaxS1;
lv_obj_t * ui_TextHumMaximaS1;
void ui_event_ButtonBack3(lv_event_t * e);
lv_obj_t * ui_ButtonBack3;
lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

// SCREEN: ui_BalanceDiarioS2
void ui_BalanceDiarioS2_screen_init(void);
lv_obj_t * ui_BalanceDiarioS2;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_BalanceTempTextMinS2;
lv_obj_t * ui_TextTempMinimaS2;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_BalanceTempTextMaxS2;
lv_obj_t * ui_TextTempMaximaS2;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_BalanceHumTextMinS2;
lv_obj_t * ui_TextHumMinimaS2;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_BalanceHumMaxS2;
lv_obj_t * ui_TextHumMaximaS2;
void ui_event_ButtonBack4(lv_event_t * e);
lv_obj_t * ui_ButtonBack4;
lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_RANGOSSectoresDPV
void ui_RANGOSSectoresDPV_screen_init(void);
lv_obj_t * ui_RANGOSSectoresDPV;
void ui_event_BackButtomRa7(lv_event_t * e);
lv_obj_t * ui_BackButtomRa7;
lv_obj_t * ui_BackText7;
void ui_event_MenuButtomRa9(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa9;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel20;
void ui_event_Sector1ConfigDPVmin(lv_event_t * e);
lv_obj_t * ui_Sector1ConfigDPVmin;
lv_obj_t * ui_DPVmintextS1;
void ui_event_Sector1ConfigDPVmax(lv_event_t * e);
lv_obj_t * ui_Sector1ConfigDPVmax;
lv_obj_t * ui_DPVmaxtextS1;
void ui_event_Sector2ConfigDPVmin(lv_event_t * e);
lv_obj_t * ui_Sector2ConfigDPVmin;
lv_obj_t * ui_DPVmintextS2;
void ui_event_Sector2ConfigDPVmax(lv_event_t * e);
lv_obj_t * ui_Sector2ConfigDPVmax;
lv_obj_t * ui_DPVmaxtextS2;
void ui_event_ButtonInfo(lv_event_t * e);
lv_obj_t * ui_ButtonInfo;
lv_obj_t * ui_textINFO;
// CUSTOM VARIABLES

// SCREEN: ui_RANGOSDPVS1MIN
void ui_RANGOSDPVS1MIN_screen_init(void);
lv_obj_t * ui_RANGOSDPVS1MIN;
void ui_event_BackButtomRa2(lv_event_t * e);
lv_obj_t * ui_BackButtomRa2;
lv_obj_t * ui_BackText2;
void ui_event_MenuButtomRa3(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_ConsignaDPVMinTextS1;
lv_obj_t * ui_DPVMINS1Text;
lv_obj_t * ui_ButtonDecreDPVminS1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_ButtonIncreDPVminS1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_consignaDPVMinS1;
lv_obj_t * ui_Label8;


// SCREEN: ui_RANGOSDPVS2MIN
void ui_RANGOSDPVS2MIN_screen_init(void);
lv_obj_t * ui_RANGOSDPVS2MIN;
void ui_event_BackButtomRa1(lv_event_t * e);
lv_obj_t * ui_BackButtomRa1;
lv_obj_t * ui_BackText1;
void ui_event_MenuButtomRa1(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_ConsignaDPVMinTextS2;
lv_obj_t * ui_DPVMINS2Text;
lv_obj_t * ui_ButtonDecreDPVminS2;
lv_obj_t * ui_Label15;
lv_obj_t * ui_ButtonIncreDPVminS2;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_consignaDPVMinS2;
lv_obj_t * ui_Label17;

// CUSTOM VARIABLES

// SCREEN: ui_RANGOSDPVS1MAX
void ui_RANGOSDPVS1MAX_screen_init(void);
lv_obj_t * ui_RANGOSDPVS1MAX;
void ui_event_BackButtomRa3(lv_event_t * e);
lv_obj_t * ui_BackButtomRa3;
lv_obj_t * ui_BackText3;
void ui_event_MenuButtomRa2(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa2;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_ConsignaDPVMaxTextS1;
lv_obj_t * ui_DPVMAXS1Text;
lv_obj_t * ui_ButtonDecreDPVmaxS1;
lv_obj_t * ui_Label19;
lv_obj_t * ui_ButtonIncreDPVmaxS1;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_consignaDPVMaxS1;
lv_obj_t * ui_Label21;

// CUSTOM VARIABLES

// SCREEN: ui_RANGOSDPVS2MAX
void ui_RANGOSDPVS2MAX_screen_init(void);
lv_obj_t * ui_RANGOSDPVS2MAX;
void ui_event_BackButtomRa6(lv_event_t * e);
lv_obj_t * ui_BackButtomRa6;
lv_obj_t * ui_BackText6;
void ui_event_MenuButtomRa5(lv_event_t * e);
lv_obj_t * ui_MenuButtomRa5;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_ConsignaDPVMaxTextS2;
lv_obj_t * ui_DPVMAXS2Text;
lv_obj_t * ui_ButtonDecreDPVmaxS2;
lv_obj_t * ui_Label23;
lv_obj_t * ui_ButtonIncreDPVmaxS2;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_consignaDPVMaxS2;
lv_obj_t * ui_Label25;

// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

//////////////////////OWN_FUNCTIONS////////////////// (Funciones de consignas por pantañña)
#include "lvgl.h"


/*static void check_switch_state(lv_timer_t * timer) {
    lv_obj_t *sw = (lv_obj_t *)lv_timer_get_user_data(timer);

    if (lv_obj_has_state(sw, LV_STATE_CHECKED)) {
        ESP_LOGI("SWITCH", " Automatismo DESACTIVADO (switch ON)");
    } else {
        ESP_LOGI("SWITCH", " Automatismo ACTIVADO (switch OFF)");
    }

    // Eliminar el timer una vez ejecutado
    lv_timer_del(timer);
}*/

void ui_event_SwitchDesactivarAutomatismo(lv_event_t * e) {
    lv_obj_t *sw = lv_event_get_target(e);
	int aux = 0;

      if (lv_obj_has_state(sw, LV_STATE_CHECKED)) {
        ESP_LOGI("SWITCH", " Automatismo ACTIVADO (switch OFF)");
         lv_obj_clear_state(sw, LV_STATE_CHECKED);
         aux = 0;
    } else {
        
         ESP_LOGI("SWITCH", " Automatismo DESACTIVADO (switch ON)");
         lv_obj_add_state(sw, LV_STATE_CHECKED);
         aux = 1;
    }
    
    ConsignasLVGL evento = {
        .tipo = EVENTO_DESACTIVAR_AUTOMATISMO,
        .valor = aux,  
    };

    xQueueSend(cola_consignas, &evento, 0);
}

void ui_event_MenuButtomRa1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}


void ui_event_ActivarNebulizacionS1(lv_event_t * e) {
    lv_obj_t *sw = lv_event_get_target(e);
	int aux = 0;
	
    if (lv_obj_has_state(sw, LV_STATE_CHECKED)) {
        ESP_LOGI("SWITCH", " Nebulizacion SECTOR1 DESACTIVADO (switch OFF)");
        lv_obj_clear_state(sw, LV_STATE_CHECKED);
        // Lógica para desactivar nebulización S1
        aux = 0;
    } else {
        
        ESP_LOGI("SWITCH", " Nebulizacion SECTOR1 ACTIVADO (switch ON)");
        lv_obj_add_state(sw, LV_STATE_CHECKED);
        // Lógica para activar nebulización S1
        aux = 1;
    }
     ConsignasLVGL evento = {
        .tipo = EVENTO_NEBULIZARS1,
        .valor = aux,  
    };
//donde recibo esto hacer tambien un publish de mqtt para que este la pantalla local como la online (Sincronizada)
    xQueueSend(cola_consignas, &evento, 0);
}




void ui_event_ActivarNebulizacionS2(lv_event_t * e) {
    lv_obj_t *sw = lv_event_get_target(e);
    int aux = 0;

      if (lv_obj_has_state(sw, LV_STATE_CHECKED)) {
        ESP_LOGI("SWITCH", " Nebulizacion SECTOR2 DESACTIVADO (switch OFF)");
        lv_obj_clear_state(sw, LV_STATE_CHECKED);
        // Lógica para desactivar nebulización S2
        aux = 0;
    } else {
        
        ESP_LOGI("SWITCH", " Nebulizacion SECTOR2 ACTIVADO (switch ON)");
        lv_obj_add_state(sw, LV_STATE_CHECKED);
        // Lógica para activar nebulización S2
        aux = 1;
    }
    
    ConsignasLVGL evento = {
        .tipo = EVENTO_NEBULIZARS2,
        .valor = aux,  
    };

    xQueueSend(cola_consignas, &evento, 0);
}

void increment_event_handler(lv_event_t * e) {
    lv_obj_t *label = (lv_obj_t *)lv_event_get_user_data(e);
	
	if (label == ui_consignaDPVMinS1) 
	{
    	consigna_screen = EVENTO_DPV_MINS1;
	} 
	else if (label == ui_consignaDPVMinS2) 
	{
    	consigna_screen = EVENTO_DPV_MINS2;
	}
	else if(label == ui_consignaDPVMaxS1)
	{
		consigna_screen = EVENTO_DPV_MAXS1;
	}
	else if(label == ui_consignaDPVMaxS2)
	{
		consigna_screen = EVENTO_DPV_MAXS2;
	}
	
    if (!lv_obj_is_valid(label)) {
        printf(" El label NO es válido\n");
        return;
    }

    const char *txt = lv_label_get_text(label);
    if (txt == NULL) {
        printf(" Texto del label es NULL\n");
        return;
    }

    float num = atof(txt);
    num += 0.1f;

    char buf[16];
    snprintf(buf, sizeof(buf), "%.1f", num);
    lv_label_set_text(label, buf);
    
     ConsignasLVGL evento = {
        .tipo = consigna_screen,
        .valor = (int)(num * 10),  // ejemplo: pasamos 0.1 como 1
    };

    xQueueSend(cola_consignas, &evento, 0);
}


void decrement_event_handler(lv_event_t * e) {
	
	lv_obj_t * label = (lv_obj_t *)lv_event_get_user_data(e);  // El label está en user data
	
	if (label == ui_consignaDPVMinS1) 
	{
    	consigna_screen = EVENTO_DPV_MINS1;
	} 
	else if (label == ui_consignaDPVMinS2) 
	{
    	consigna_screen = EVENTO_DPV_MINS2;
	}
	else if(label == ui_consignaDPVMaxS1)
	{
		consigna_screen = EVENTO_DPV_MAXS1;
	}
	else if(label == ui_consignaDPVMaxS2)
	{
		consigna_screen = EVENTO_DPV_MAXS2;
	}
	
   if (label == NULL) {
        printf(" Error: user_data (label) es NULL\n");
        return;
    }

    const char * txt = lv_label_get_text(label);
    if (txt == NULL) {
        printf("Error: texto del label es NULL\n");
        return;
    }

    float num = atof(txt);  // convertir a float
    if(num>0)
    {
    	num -= 0.1f;
    }

    char buf[16];
    snprintf(buf, sizeof(buf), "%.1f", num);  // usar formato float
    lv_label_set_text(label, buf);
    
       ConsignasLVGL evento = {
        .tipo = consigna_screen,
        .valor = (int)(num * 10),  // ejemplo: pasamos 0.1 como 1
    };

    xQueueSend(cola_consignas, &evento, 0);
}
///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonAmbiente(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SECTORES, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SECTORES_screen_init);
    }
}

void ui_event_ButtonSuelo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SUELO, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SUELO_screen_init);
    }
}


void ui_event_ButtonGraficas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficasAmbiente, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficasAmbiente_screen_init);
    }
}

void ui_event_ButtonConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_CONFIGURACION, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CONFIGURACION_screen_init);
    }
}

void ui_event_botonmenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_MenuButtomRa5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}
void ui_event_BackButtomRa6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_BackButtomRa5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficasAmbiente, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficasAmbiente_screen_init);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SECTORES, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SECTORES_screen_init);
    }
}

void ui_event_MenuBotonSoil(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_ButtonMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_BackButtomRa3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_SECTOR1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AMBIENTES1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AMBIENTES1_screen_init);
    }
}

void ui_event_SECTOR2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AMBIENTES2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AMBIENTES2_screen_init);
    }
}

void ui_event_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SECTORES, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SECTORES_screen_init);
    }
}

void ui_event_MenuButtom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_BackButtomNeb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_CONFIGURACION, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CONFIGURACION_screen_init);
    }
}

void ui_event_ButtonNebulizar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Nebulizar, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Nebulizar_screen_init);
    }
}

void ui_event_ButtonRangos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_ButtonMenu2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_MENUText2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_BackButtomRa2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_MenuButtomRa3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}


void ui_event_ButtonInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenINFODPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenINFODPV_screen_init);
    }
}


void ui_event_MenuButtomRa4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_ButtonTempS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficaTempHumS1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficaTempHumS1_screen_init);
    }
}

void ui_event_ButtonTempS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficaTempHumS2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficaTempHumS2_screen_init);
    }
}

void ui_event_ButtonBalanceDiarioS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BalanceDiarioS1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BalanceDiarioS1_screen_init);
    }
}

void ui_event_ButtonBalanceDIarioS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BalanceDiarioS2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BalanceDiarioS2_screen_init);
    }
}



void ui_event_Sector1ConfigDPVmin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSDPVS1MIN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSDPVS1MIN_screen_init);
    }
}

void ui_event_Sector1ConfigDPVmax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSDPVS1MAX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSDPVS1MAX_screen_init);
    }
}

void ui_event_Sector2ConfigDPVmin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSDPVS2MIN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSDPVS2MIN_screen_init);
    }
}

void ui_event_Sector2ConfigDPVmax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSDPVS2MAX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSDPVS2MAX_screen_init);
    }
}

void ui_event_BackButtomRa4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficasAmbiente, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficasAmbiente_screen_init);
    }
}

void ui_event_BackButtomRa7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_CONFIGURACION, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CONFIGURACION_screen_init);
    }
}

void ui_event_MenuButtomRa9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}

void ui_event_ButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_ButtonBack3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficasAmbiente, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficasAmbiente_screen_init);
    }
}

void ui_event_ButtonBack4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GraficasAmbiente, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraficasAmbiente_screen_init);
    }
}

void ui_event_BackButtomRa1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RANGOSSectoresDPV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RANGOSSectoresDPV_screen_init);
    }
}

void ui_event_MenuButtomRa2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Inicio_screen_init);
    }
}





///////////////////// SCREENS ////////////////////
/*MIO*/
void ui_limpiar_sombra(lv_obj_t * obj) {
   // Eliminar sombras (causan gran consumo por los buffers de esquina)
    lv_obj_set_style_shadow_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(obj, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);

    //  Eliminar bordes innecesarios 
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    //  Eliminar padding
    lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    //  Eliminar margen
    lv_obj_set_style_margin_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    //  Desactivar scroll si no lo usas (puede generar cálculos extra)
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);

    //  Opcional: fondo transparente si no necesitas color
    // lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}

//char texto[32];
void float_to_text(float value, char *buffer, int precision)
{
    snprintf(buffer, SENSOR_STR_SIZE, "%.*f", precision, value);
}

// Supongamos que tienes un label llamado ui_VALORtempS1

void actualizar_label_con_float(float temp, char *text)
{

    float_to_text(temp, text, 2);  // 1 decimal → 23.4 por ejemplo
}

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Menu_Inicio_screen_init();
   /*ui_AMBIENTES1_screen_init();
    ui_SUELO_screen_init();
    ui_SECTORES_screen_init();
    ui_AMBIENTES2_screen_init();
    ui_Nebulizar_screen_init();
    ui_CONFIGURACION_screen_init();
    ui_RANGOSDPVS1MIN_screen_init();
    ui_GraficasAmbiente_screen_init();
    ui_GraficaTempHumS1_screen_init();
    ui_ScreenINFODPV_screen_init();
    ui_GraficaTempHumS2_screen_init();
    ui_RANGOSSectoresDPV_screen_init();
    ui_BalanceDiarioS1_screen_init();
    ui_BalanceDiarioS2_screen_init();
    ui_RANGOSDPVS2MIN_screen_init();
    ui_RANGOSDPVS1MAX_screen_init();
    ui_RANGOSDPVS2MAX_screen_init();*/
    
    ui____initial_actions0 = lv_obj_create( NULL);//
    lv_disp_load_scr(ui_Menu_Inicio);
    //actualizar_label_con_float(27.32);
}


