// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "freertos/FreeRTOS.h"
//Buffers de los datos de los sensores
#define SENSOR_STR_SIZE 12  

typedef struct {
    char dpv[SENSOR_STR_SIZE];
    char temp_amb[SENSOR_STR_SIZE];
    char hum_amb[SENSOR_STR_SIZE];
} SensorAmbData;

extern SensorAmbData SectorS1Amb;
extern SensorAmbData SectorS2Amb;

typedef struct {
    char hum[ SENSOR_STR_SIZE ];
    char temp[ SENSOR_STR_SIZE ];
    char ph[ SENSOR_STR_SIZE ];
    char conduc[ SENSOR_STR_SIZE ];
} SoilData;

//char estadoRele1;
//char estadoRele2;
extern SoilData SoilData1;
//Cola de consignas por pantalla
extern QueueHandle_t cola_consignas;

// Enumeración para tipo de evento
typedef enum {
    EVENTO_DPV_MINS1,
    EVENTO_DPV_MAXS1,
    EVENTO_DPV_MINS2,
    EVENTO_DPV_MAXS2,
    EVENTO_DESACTIVAR_AUTOMATISMO,
    EVENTO_NEBULIZARS1,
    EVENTO_NEBULIZARS2
} TipoConsigna;

// Estructura del mensaje que se pasa por la cola
typedef struct {
    TipoConsigna tipo;
    int valor;
    //uint32_t timestamp;
} ConsignasLVGL;


typedef struct {
    char DPVminS1[ SENSOR_STR_SIZE ];
    char DPVmaxS1[ SENSOR_STR_SIZE ];
    char DPVminS2[ SENSOR_STR_SIZE ];
    char DPVmaxS2[ SENSOR_STR_SIZE ];
} ConsignasDPV;

extern ConsignasDPV consignasDPV;
///
typedef struct {
    char valor[SENSOR_STR_SIZE];
    volatile bool actualizado;  //  Solo se pone en true si cambia el valor
} DatoLVGLtemporal;

typedef struct {
    bool estadoReles;
    volatile bool actualizado;  //  Solo se pone en true si cambia el valor
} DatoLVGLbooltemporal;

extern DatoLVGLtemporal temp_S1;
extern DatoLVGLtemporal hum_S1;
extern DatoLVGLtemporal temp_S2;
extern DatoLVGLtemporal hum_S2;
extern DatoLVGLtemporal temp_suelo;
extern DatoLVGLtemporal hum_suelo;
extern DatoLVGLtemporal cond_suelo;
extern DatoLVGLtemporal ph_suelo;
extern DatoLVGLtemporal DPVS1;
extern DatoLVGLtemporal DPVS2;
extern DatoLVGLtemporal DPVminS1;
extern DatoLVGLtemporal DPVminS2;
extern DatoLVGLtemporal DPVmaxS1;
extern DatoLVGLtemporal DPVmaxS2;

extern DatoLVGLbooltemporal Rele1;
extern DatoLVGLbooltemporal Rele2;
extern DatoLVGLbooltemporal estado_automatismo;
///
void actualizar_label_con_float(float temp, char *text);//le paso un float de la lectura del sensor y lo convierte a texto!
void increment_event_handler(lv_event_t * e);
void decrement_event_handler(lv_event_t * e);
void ui_limpiar_sombra(lv_obj_t * obj);
///

// SCREEN: ui_Menu_Inicio
void ui_Menu_Inicio_screen_init(void);
extern lv_obj_t * ui_Menu_Inicio;
extern lv_obj_t * ui_Panel3;
void ui_event_ButtonAmbiente(lv_event_t * e);
extern lv_obj_t * ui_ButtonAmbiente;
extern lv_obj_t * ui_ambientetext;
void ui_event_ButtonSuelo(lv_event_t * e);
extern lv_obj_t * ui_ButtonSuelo;
extern lv_obj_t * ui_suelotext;
extern lv_obj_t * ui_Panel4;
void ui_event_ButtonGraficas(lv_event_t * e);
extern lv_obj_t * ui_ButtonGraficas;
extern lv_obj_t * ui_graficasname;
extern lv_obj_t * ui_Panel5;
void ui_event_ButtonConfig(lv_event_t * e);
extern lv_obj_t * ui_ButtonConfig;
extern lv_obj_t * ui_ConfigName;
// CUSTOM VARIABLES

// SCREEN: ui_AMBIENTES1
void ui_AMBIENTES1_screen_init(void);
extern lv_obj_t * ui_AMBIENTES1;
extern lv_obj_t * ui_TEMPERATURA1;
extern lv_obj_t * ui_temperaturaindicator1;
extern lv_obj_t * ui_HUMEDAD1;
extern lv_obj_t * ui_humedadindicator1;
void ui_event_botonmenu1(lv_event_t * e);
extern lv_obj_t * ui_botonmenu1;
extern lv_obj_t * ui_menutext1;
extern lv_obj_t * ui_humedadtext;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_botonbacktext;
extern lv_obj_t * ui_temperatura1text;
extern lv_obj_t * ui_VALORtempS1;
extern lv_obj_t * ui_VALORhumS1;
extern lv_obj_t * ui_PanelDPVS1;
extern lv_obj_t * ui_DPV1text;
extern lv_obj_t * ui_VALORDPVS1;
// CUSTOM VARIABLES

// SCREEN: ui_SUELO
void ui_SUELO_screen_init(void);
extern lv_obj_t * ui_SUELO;
extern lv_obj_t * ui_TemperaturaSuelo1;
extern lv_obj_t * ui_barraTempSuelo;
void ui_event_MenuBotonSoil(lv_event_t * e);
extern lv_obj_t * ui_MenuBotonSoil;
extern lv_obj_t * ui_menutext3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_HUMEDADSUELO1;
extern lv_obj_t * ui_barraHumSuelo;
extern lv_obj_t * ui_CONDUCTIVIDAD;
extern lv_obj_t * ui_barraConducSuelo;
extern lv_obj_t * ui_PPPPHHH;
extern lv_obj_t * ui_barrPHSuelo;
extern lv_obj_t * ui_humsuelo;
extern lv_obj_t * ui_conducsuelo;
extern lv_obj_t * ui_phsuelo;
extern lv_obj_t * ui_VALORtempSuelo;
extern lv_obj_t * ui_VALORhumSuelo;
extern lv_obj_t * ui_VALORConducSuelo;
extern lv_obj_t * ui_VALORPHSuelo;
// CUSTOM VARIABLES

// SCREEN: ui_SECTORES
void ui_SECTORES_screen_init(void);
extern lv_obj_t * ui_SECTORES;
void ui_event_ButtonMenu(lv_event_t * e);
extern lv_obj_t * ui_ButtonMenu;
extern lv_obj_t * ui_menutext;
void ui_event_SECTOR1(lv_event_t * e);
extern lv_obj_t * ui_SECTOR1;
extern lv_obj_t * ui_sector1text;
void ui_event_SECTOR2(lv_event_t * e);
extern lv_obj_t * ui_SECTOR2;
extern lv_obj_t * ui_sector2text;
// CUSTOM VARIABLES

// SCREEN: ui_AMBIENTES2
void ui_AMBIENTES2_screen_init(void);
extern lv_obj_t * ui_AMBIENTES2;
void ui_event_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_MenuButton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TEMPERATURAS2;
extern lv_obj_t * ui_tamperaturaindicator2;
extern lv_obj_t * ui_HUMEDADS2;
extern lv_obj_t * ui_humedadindicator2;
extern lv_obj_t * ui_temperaturatext2;
extern lv_obj_t * ui_humedadtext2;
void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_VALORtempS2;
extern lv_obj_t * ui_VALORhumS2;
extern lv_obj_t * ui_PanelDPVS2;
extern lv_obj_t * ui_DPV2text;
extern lv_obj_t * ui_VALORDPVS2;
// CUSTOM VARIABLES

// SCREEN: ui_Nebulizar
void ui_Nebulizar_screen_init(void);
extern lv_obj_t * ui_Nebulizar;
void ui_event_MenuButtom(lv_event_t * e);
extern lv_obj_t * ui_MenuButtom;
extern lv_obj_t * ui_menutextconf;
extern lv_obj_t * ui_NEBULIZAR_SECTOR1;
extern lv_obj_t * ui_NEBULIZAR_SECTOR2;
extern lv_obj_t * ui_S1NEB;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_S2NEB;
extern lv_obj_t * ui_Label4;
void ui_event_BackButtomNeb(lv_event_t * e);
extern lv_obj_t * ui_BackButtomNeb;
extern lv_obj_t * ui_BackButtomText;
// CUSTOM VARIABLES

// SCREEN: ui_CONFIGURACION
void ui_CONFIGURACION_screen_init(void);
extern lv_obj_t * ui_CONFIGURACION;
extern lv_obj_t * ui_Panel1;
void ui_event_ButtonNebulizar(lv_event_t * e);
extern lv_obj_t * ui_ButtonNebulizar;
extern lv_obj_t * ui_Nebulizartext;
extern lv_obj_t * ui_Panel2;
void ui_event_ButtonRangos(lv_event_t * e);
extern lv_obj_t * ui_ButtonRangos;
extern lv_obj_t * ui_RANGOStext;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_SwitchDesactivarAutomatismo;
extern lv_obj_t * ui_Label14;
void ui_event_ButtonMenu2(lv_event_t * e);
extern lv_obj_t * ui_ButtonMenu2;
void ui_event_MENUText2(lv_event_t * e);
extern lv_obj_t * ui_MENUText2;
// CUSTOM VARIABLES


// SCREEN: ui_GraficasAmbiente
void ui_GraficasAmbiente_screen_init(void);
extern lv_obj_t * ui_GraficasAmbiente;
void ui_event_MenuButtomRa4(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa4;
extern lv_obj_t * ui_menutext6;
extern lv_obj_t * ui_Panel11;
void ui_event_ButtonTempS1(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempS1;
extern lv_obj_t * ui_ButtomTempS1Text;
void ui_event_ButtonTempS2(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempS2;
extern lv_obj_t * ui_ButtomTempS2Text;
void ui_event_ButtonBalanceDiarioS1(lv_event_t * e);
extern lv_obj_t * ui_ButtonBalanceDiarioS1;
extern lv_obj_t * ui_BalanceDiarioS1Text;
void ui_event_ButtonBalanceDIarioS2(lv_event_t * e);
extern lv_obj_t * ui_ButtonBalanceDIarioS2;
extern lv_obj_t * ui_BalanceDiarioS2Text;
// CUSTOM VARIABLES

// SCREEN: ui_GraficaTempHumS1
void ui_GraficaTempHumS1_screen_init(void);
extern lv_obj_t * ui_GraficaTempHumS1;
void ui_event_BackButtomRa5(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa5;
extern lv_obj_t * ui_BackText5;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_temptext;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_humText;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenINFODPV
void ui_ScreenINFODPV_screen_init(void);
extern lv_obj_t * ui_ScreenINFODPV;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label32;
void ui_event_ButtonBack(lv_event_t * e);
extern lv_obj_t * ui_ButtonBack;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

// SCREEN: ui_GraficaTempHumS2
void ui_GraficaTempHumS2_screen_init(void);
extern lv_obj_t * ui_GraficaTempHumS2;
void ui_event_BackButtomRa4(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa4;
extern lv_obj_t * ui_BackText4;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_temptext1;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_humText1;
// CUSTOM VARIABLES


// SCREEN: ui_BalanceDiarioS1
void ui_BalanceDiarioS1_screen_init(void);
extern lv_obj_t * ui_BalanceDiarioS1;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_BalanceTempTextMinS1;
extern lv_obj_t * ui_TextTempMinimaS1;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_BalanceTempTextMaxS1;
extern lv_obj_t * ui_TextTempMaximaS1;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_BalanceHumTextMinS1;
extern lv_obj_t * ui_TextHumMinimaS1;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_BalanceHumMaxS1;
extern lv_obj_t * ui_TextHumMaximaS1;
void ui_event_ButtonBack3(lv_event_t * e);
extern lv_obj_t * ui_ButtonBack3;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

// SCREEN: ui_BalanceDiarioS2
void ui_BalanceDiarioS2_screen_init(void);
extern lv_obj_t * ui_BalanceDiarioS2;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_BalanceTempTextMinS2;
extern lv_obj_t * ui_TextTempMinimaS2;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_BalanceTempTextMaxS2;
extern lv_obj_t * ui_TextTempMaximaS2;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_BalanceHumTextMinS2;
extern lv_obj_t * ui_TextHumMinimaS2;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_BalanceHumMaxS2;
extern lv_obj_t * ui_TextHumMaximaS2;
void ui_event_ButtonBack4(lv_event_t * e);
extern lv_obj_t * ui_ButtonBack4;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_RANGOSSectoresDPV
void ui_RANGOSSectoresDPV_screen_init(void);
extern lv_obj_t * ui_RANGOSSectoresDPV;
void ui_event_BackButtomRa7(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa7;
extern lv_obj_t * ui_BackText7;
void ui_event_MenuButtomRa9(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa9;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel20;
void ui_event_Sector1ConfigDPVmin(lv_event_t * e);
extern lv_obj_t * ui_Sector1ConfigDPVmin;
extern lv_obj_t * ui_DPVmintextS1;
void ui_event_Sector1ConfigDPVmax(lv_event_t * e);
extern lv_obj_t * ui_Sector1ConfigDPVmax;
extern lv_obj_t * ui_DPVmaxtextS1;
void ui_event_Sector2ConfigDPVmin(lv_event_t * e);
extern lv_obj_t * ui_Sector2ConfigDPVmin;
extern lv_obj_t * ui_DPVmintextS2;
void ui_event_Sector2ConfigDPVmax(lv_event_t * e);
extern lv_obj_t * ui_Sector2ConfigDPVmax;
extern lv_obj_t * ui_DPVmaxtextS2;
void ui_event_ButtonInfo(lv_event_t * e);
extern lv_obj_t * ui_ButtonInfo;
extern lv_obj_t * ui_textINFO;
// CUSTOM VARIABLES

// SCREEN: ui_RANGOSDPVS1MIN
void ui_RANGOSDPVS1MIN_screen_init(void);
extern lv_obj_t * ui_RANGOSDPVS1MIN;
void ui_event_BackButtomRa2(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa2;
extern lv_obj_t * ui_BackText2;
void ui_event_MenuButtomRa3(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_ConsignaDPVMinTextS1;
extern lv_obj_t * ui_DPVMINS1Text;
extern lv_obj_t * ui_ButtonDecreDPVminS1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ButtonIncreDPVminS1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_consignaDPVMinS1;
extern lv_obj_t * ui_Label8;


// SCREEN: ui_RANGOSDPVS2MIN
void ui_RANGOSDPVS2MIN_screen_init(void);
extern lv_obj_t * ui_RANGOSDPVS2MIN;
void ui_event_BackButtomRa1(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa1;
extern lv_obj_t * ui_BackText1;
void ui_event_MenuButtomRa1(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_ConsignaDPVMinTextS2;
extern lv_obj_t * ui_DPVMINS2Text;
extern lv_obj_t * ui_ButtonDecreDPVminS2;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_ButtonIncreDPVminS2;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_consignaDPVMinS2;
extern lv_obj_t * ui_Label17;


// SCREEN: ui_RANGOSDPVS1MAX
void ui_RANGOSDPVS1MAX_screen_init(void);
extern lv_obj_t * ui_RANGOSDPVS1MAX;
void ui_event_BackButtomRa3(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa3;
extern lv_obj_t * ui_BackText3;
void ui_event_MenuButtomRa2(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_ConsignaDPVMaxTextS1;
extern lv_obj_t * ui_DPVMAXS1Text;
extern lv_obj_t * ui_ButtonDecreDPVmaxS1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_ButtonIncreDPVmaxS1;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_consignaDPVMaxS1;
extern lv_obj_t * ui_Label21;

// CUSTOM VARIABLES

// SCREEN: ui_RANGOSDPVS2MAX
void ui_RANGOSDPVS2MAX_screen_init(void);
extern lv_obj_t * ui_RANGOSDPVS2MAX;
void ui_event_BackButtomRa6(lv_event_t * e);
extern lv_obj_t * ui_BackButtomRa6;
extern lv_obj_t * ui_BackText6;
void ui_event_MenuButtomRa5(lv_event_t * e);
extern lv_obj_t * ui_MenuButtomRa5;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_ConsignaDPVMaxTextS2;
extern lv_obj_t * ui_DPVMAXS2Text;
extern lv_obj_t * ui_ButtonDecreDPVmaxS2;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_ButtonIncreDPVmaxS2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_consignaDPVMaxS2;
extern lv_obj_t * ui_Label25;

// CUSTOM VARIABLES

//Funciones de consigna:
void ui_event_SwitchDesactivarAutomatismo(lv_event_t * e);
void ui_event_ActivarNebulizacionS1(lv_event_t * e);
void ui_event_ActivarNebulizacionS2(lv_event_t * e);

// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
